export interface Emoji {
  char: string;
  name: string;
  category: string;
  keywords: string[];
}

export const CATEGORIES = [
  "All", "Faces", "People", "Animals", "Food", "Travel",
  "Activities", "Objects", "Symbols", "Flags",
];

export const EMOJIS: Emoji[] = [
  // Faces
  { char: "😀", name: "grinning face", category: "Faces", keywords: ["happy", "smile", "grin"] },
  { char: "😃", name: "grinning face with big eyes", category: "Faces", keywords: ["happy", "smile"] },
  { char: "😄", name: "grinning face with smiling eyes", category: "Faces", keywords: ["happy", "smile"] },
  { char: "😁", name: "beaming face with smiling eyes", category: "Faces", keywords: ["grin", "happy"] },
  { char: "😆", name: "grinning squinting face", category: "Faces", keywords: ["laugh", "lol"] },
  { char: "😅", name: "grinning face with sweat", category: "Faces", keywords: ["nervous", "sweat"] },
  { char: "🤣", name: "rolling on the floor laughing", category: "Faces", keywords: ["rofl", "lol", "laugh"] },
  { char: "😂", name: "face with tears of joy", category: "Faces", keywords: ["lol", "laugh", "crying"] },
  { char: "🙂", name: "slightly smiling face", category: "Faces", keywords: ["smile", "happy"] },
  { char: "🙃", name: "upside-down face", category: "Faces", keywords: ["silly", "sarcasm"] },
  { char: "😉", name: "winking face", category: "Faces", keywords: ["wink", "flirt"] },
  { char: "😊", name: "smiling face with smiling eyes", category: "Faces", keywords: ["smile", "blush"] },
  { char: "😇", name: "smiling face with halo", category: "Faces", keywords: ["angel", "innocent"] },
  { char: "🥰", name: "smiling face with hearts", category: "Faces", keywords: ["love", "hearts"] },
  { char: "😍", name: "smiling face with heart-eyes", category: "Faces", keywords: ["love", "heart"] },
  { char: "🤩", name: "star-struck", category: "Faces", keywords: ["stars", "excited", "wow"] },
  { char: "😘", name: "face blowing a kiss", category: "Faces", keywords: ["kiss", "love"] },
  { char: "😗", name: "kissing face", category: "Faces", keywords: ["kiss"] },
  { char: "😙", name: "kissing face with smiling eyes", category: "Faces", keywords: ["kiss", "smile"] },
  { char: "😚", name: "kissing face with closed eyes", category: "Faces", keywords: ["kiss"] },
  { char: "😋", name: "face savoring food", category: "Faces", keywords: ["yummy", "delicious", "tasty"] },
  { char: "😛", name: "face with tongue", category: "Faces", keywords: ["tongue", "playful"] },
  { char: "😜", name: "winking face with tongue", category: "Faces", keywords: ["tongue", "playful", "wink"] },
  { char: "🤪", name: "zany face", category: "Faces", keywords: ["crazy", "silly"] },
  { char: "😝", name: "squinting face with tongue", category: "Faces", keywords: ["tongue", "tease"] },
  { char: "🤑", name: "money-mouth face", category: "Faces", keywords: ["money", "rich"] },
  { char: "🤗", name: "smiling face with open hands", category: "Faces", keywords: ["hug", "warm"] },
  { char: "🤭", name: "face with hand over mouth", category: "Faces", keywords: ["oops", "secret"] },
  { char: "🤫", name: "shushing face", category: "Faces", keywords: ["quiet", "secret", "shhh"] },
  { char: "🤔", name: "thinking face", category: "Faces", keywords: ["think", "hmm", "pondering"] },
  { char: "🤐", name: "zipper-mouth face", category: "Faces", keywords: ["silent", "secret", "zip"] },
  { char: "🤨", name: "face with raised eyebrow", category: "Faces", keywords: ["skeptical", "doubt"] },
  { char: "😐", name: "neutral face", category: "Faces", keywords: ["neutral", "meh"] },
  { char: "😑", name: "expressionless face", category: "Faces", keywords: ["blank", "expressionless"] },
  { char: "😶", name: "face without mouth", category: "Faces", keywords: ["silent", "quiet"] },
  { char: "😏", name: "smirking face", category: "Faces", keywords: ["smirk", "smug"] },
  { char: "😒", name: "unamused face", category: "Faces", keywords: ["unamused", "meh"] },
  { char: "🙄", name: "face with rolling eyes", category: "Faces", keywords: ["eyeroll", "whatever"] },
  { char: "😬", name: "grimacing face", category: "Faces", keywords: ["grimace", "awkward"] },
  { char: "🤥", name: "lying face", category: "Faces", keywords: ["lie", "pinocchio"] },
  { char: "😌", name: "relieved face", category: "Faces", keywords: ["relief", "calm"] },
  { char: "😔", name: "pensive face", category: "Faces", keywords: ["sad", "pensive"] },
  { char: "😪", name: "sleepy face", category: "Faces", keywords: ["sleepy", "tired"] },
  { char: "🤤", name: "drooling face", category: "Faces", keywords: ["drool", "food"] },
  { char: "😴", name: "sleeping face", category: "Faces", keywords: ["sleep", "zzz"] },
  { char: "😷", name: "face with medical mask", category: "Faces", keywords: ["sick", "mask", "ill"] },
  { char: "🤒", name: "face with thermometer", category: "Faces", keywords: ["sick", "ill", "fever"] },
  { char: "🤕", name: "face with head-bandage", category: "Faces", keywords: ["hurt", "injury"] },
  { char: "🤢", name: "nauseated face", category: "Faces", keywords: ["sick", "nausea"] },
  { char: "🤮", name: "face vomiting", category: "Faces", keywords: ["vomit", "sick"] },
  { char: "🤧", name: "sneezing face", category: "Faces", keywords: ["sneeze", "sick", "cold"] },
  { char: "🥵", name: "hot face", category: "Faces", keywords: ["hot", "heat", "sweat"] },
  { char: "🥶", name: "cold face", category: "Faces", keywords: ["cold", "freeze"] },
  { char: "🥴", name: "woozy face", category: "Faces", keywords: ["dizzy", "drunk"] },
  { char: "😵", name: "face with crossed-out eyes", category: "Faces", keywords: ["dizzy", "dead"] },
  { char: "🤯", name: "exploding head", category: "Faces", keywords: ["mind blown", "shocked"] },
  { char: "🤠", name: "cowboy hat face", category: "Faces", keywords: ["cowboy", "western"] },
  { char: "🥳", name: "partying face", category: "Faces", keywords: ["party", "celebrate", "birthday"] },
  { char: "😎", name: "smiling face with sunglasses", category: "Faces", keywords: ["cool", "sunglasses"] },
  { char: "🤓", name: "nerd face", category: "Faces", keywords: ["nerd", "geek", "glasses"] },
  { char: "🧐", name: "face with monocle", category: "Faces", keywords: ["curious", "monocle"] },
  { char: "😕", name: "confused face", category: "Faces", keywords: ["confused", "unsure"] },
  { char: "😟", name: "worried face", category: "Faces", keywords: ["worried", "sad"] },
  { char: "🙁", name: "slightly frowning face", category: "Faces", keywords: ["sad", "frown"] },
  { char: "☹️", name: "frowning face", category: "Faces", keywords: ["sad", "frown"] },
  { char: "😮", name: "face with open mouth", category: "Faces", keywords: ["wow", "surprised"] },
  { char: "😯", name: "hushed face", category: "Faces", keywords: ["surprised", "quiet"] },
  { char: "😲", name: "astonished face", category: "Faces", keywords: ["shocked", "wow"] },
  { char: "😳", name: "flushed face", category: "Faces", keywords: ["embarrassed", "blush"] },
  { char: "🥺", name: "pleading face", category: "Faces", keywords: ["please", "puppy eyes"] },
  { char: "😦", name: "frowning face with open mouth", category: "Faces", keywords: ["worried", "frown"] },
  { char: "😧", name: "anguished face", category: "Faces", keywords: ["anguish", "pain"] },
  { char: "😨", name: "fearful face", category: "Faces", keywords: ["fear", "scared"] },
  { char: "😰", name: "anxious face with sweat", category: "Faces", keywords: ["anxious", "nervous"] },
  { char: "😥", name: "sad but relieved face", category: "Faces", keywords: ["sad", "relieved"] },
  { char: "😢", name: "crying face", category: "Faces", keywords: ["cry", "sad", "tear"] },
  { char: "😭", name: "loudly crying face", category: "Faces", keywords: ["cry", "sob", "sad"] },
  { char: "😱", name: "face screaming in fear", category: "Faces", keywords: ["scream", "scared"] },
  { char: "😖", name: "confounded face", category: "Faces", keywords: ["confused", "frustrated"] },
  { char: "😣", name: "persevering face", category: "Faces", keywords: ["struggling", "persevere"] },
  { char: "😞", name: "disappointed face", category: "Faces", keywords: ["disappointed", "sad"] },
  { char: "😓", name: "downcast face with sweat", category: "Faces", keywords: ["sad", "tired"] },
  { char: "😩", name: "weary face", category: "Faces", keywords: ["weary", "tired"] },
  { char: "😫", name: "tired face", category: "Faces", keywords: ["tired", "exhausted"] },
  { char: "🥱", name: "yawning face", category: "Faces", keywords: ["yawn", "tired", "bored"] },
  { char: "😤", name: "face with steam from nose", category: "Faces", keywords: ["angry", "frustrated"] },
  { char: "😡", name: "enraged face", category: "Faces", keywords: ["angry", "rage"] },
  { char: "😠", name: "angry face", category: "Faces", keywords: ["angry", "mad"] },
  { char: "🤬", name: "face with symbols on mouth", category: "Faces", keywords: ["angry", "swear"] },
  { char: "😈", name: "smiling face with horns", category: "Faces", keywords: ["devil", "evil"] },
  { char: "👿", name: "angry face with horns", category: "Faces", keywords: ["devil", "angry"] },
  { char: "💀", name: "skull", category: "Faces", keywords: ["dead", "skull", "death"] },
  { char: "☠️", name: "skull and crossbones", category: "Faces", keywords: ["danger", "poison"] },
  { char: "💩", name: "pile of poo", category: "Faces", keywords: ["poop", "poo"] },
  { char: "🤡", name: "clown face", category: "Faces", keywords: ["clown", "funny"] },
  { char: "👹", name: "ogre", category: "Faces", keywords: ["monster", "ogre"] },
  { char: "👺", name: "goblin", category: "Faces", keywords: ["goblin", "red"] },
  { char: "👻", name: "ghost", category: "Faces", keywords: ["ghost", "halloween"] },
  { char: "👽", name: "alien", category: "Faces", keywords: ["alien", "ufo", "space"] },
  { char: "🤖", name: "robot", category: "Faces", keywords: ["robot", "android", "bot"] },
  // People
  { char: "👋", name: "waving hand", category: "People", keywords: ["wave", "hello", "hi"] },
  { char: "🤚", name: "raised back of hand", category: "People", keywords: ["hand", "stop"] },
  { char: "✋", name: "raised hand", category: "People", keywords: ["hand", "stop", "high five"] },
  { char: "🖐️", name: "hand with fingers splayed", category: "People", keywords: ["hand", "five"] },
  { char: "👌", name: "ok hand", category: "People", keywords: ["ok", "okay", "perfect"] },
  { char: "🤌", name: "pinched fingers", category: "People", keywords: ["italian", "chef kiss"] },
  { char: "✌️", name: "victory hand", category: "People", keywords: ["peace", "victory", "v"] },
  { char: "🤞", name: "crossed fingers", category: "People", keywords: ["luck", "wish", "cross"] },
  { char: "🤟", name: "love-you gesture", category: "People", keywords: ["love", "rock"] },
  { char: "🤘", name: "sign of the horns", category: "People", keywords: ["rock", "metal"] },
  { char: "👍", name: "thumbs up", category: "People", keywords: ["like", "good", "approve"] },
  { char: "👎", name: "thumbs down", category: "People", keywords: ["dislike", "bad"] },
  { char: "✊", name: "raised fist", category: "People", keywords: ["fist", "power"] },
  { char: "👊", name: "oncoming fist", category: "People", keywords: ["fist", "punch"] },
  { char: "🤛", name: "left-facing fist", category: "People", keywords: ["fist bump"] },
  { char: "🤜", name: "right-facing fist", category: "People", keywords: ["fist bump"] },
  { char: "👏", name: "clapping hands", category: "People", keywords: ["clap", "applause", "bravo"] },
  { char: "🙌", name: "raising hands", category: "People", keywords: ["celebrate", "raise hands"] },
  { char: "👐", name: "open hands", category: "People", keywords: ["open", "hands"] },
  { char: "🤲", name: "palms up together", category: "People", keywords: ["please", "prayer"] },
  { char: "🤝", name: "handshake", category: "People", keywords: ["deal", "agreement", "shake"] },
  { char: "🙏", name: "folded hands", category: "People", keywords: ["pray", "please", "thanks"] },
  { char: "💪", name: "flexed biceps", category: "People", keywords: ["muscle", "strong", "flex"] },
  { char: "🦵", name: "leg", category: "People", keywords: ["leg", "kick"] },
  { char: "🦶", name: "foot", category: "People", keywords: ["foot", "kick"] },
  { char: "👂", name: "ear", category: "People", keywords: ["ear", "listen", "hear"] },
  { char: "👃", name: "nose", category: "People", keywords: ["nose", "smell"] },
  { char: "🧠", name: "brain", category: "People", keywords: ["brain", "mind", "smart"] },
  { char: "👀", name: "eyes", category: "People", keywords: ["eyes", "look", "watch"] },
  { char: "👁️", name: "eye", category: "People", keywords: ["eye", "look"] },
  { char: "👅", name: "tongue", category: "People", keywords: ["tongue"] },
  { char: "👄", name: "mouth", category: "People", keywords: ["lips", "mouth", "kiss"] },
  // Animals
  { char: "🐶", name: "dog face", category: "Animals", keywords: ["dog", "puppy", "pet"] },
  { char: "🐱", name: "cat face", category: "Animals", keywords: ["cat", "kitty", "pet"] },
  { char: "🐭", name: "mouse face", category: "Animals", keywords: ["mouse"] },
  { char: "🐹", name: "hamster", category: "Animals", keywords: ["hamster", "cute"] },
  { char: "🐰", name: "rabbit face", category: "Animals", keywords: ["rabbit", "bunny"] },
  { char: "🦊", name: "fox", category: "Animals", keywords: ["fox", "clever"] },
  { char: "🐻", name: "bear", category: "Animals", keywords: ["bear"] },
  { char: "🐼", name: "panda", category: "Animals", keywords: ["panda", "china"] },
  { char: "🐨", name: "koala", category: "Animals", keywords: ["koala", "australia"] },
  { char: "🐯", name: "tiger face", category: "Animals", keywords: ["tiger"] },
  { char: "🦁", name: "lion", category: "Animals", keywords: ["lion", "roar"] },
  { char: "🐮", name: "cow face", category: "Animals", keywords: ["cow"] },
  { char: "🐷", name: "pig face", category: "Animals", keywords: ["pig"] },
  { char: "🐸", name: "frog", category: "Animals", keywords: ["frog"] },
  { char: "🐵", name: "monkey face", category: "Animals", keywords: ["monkey", "ape"] },
  { char: "🙈", name: "see-no-evil monkey", category: "Animals", keywords: ["monkey", "evil"] },
  { char: "🙉", name: "hear-no-evil monkey", category: "Animals", keywords: ["monkey"] },
  { char: "🙊", name: "speak-no-evil monkey", category: "Animals", keywords: ["monkey"] },
  { char: "🐔", name: "chicken", category: "Animals", keywords: ["chicken", "bird"] },
  { char: "🐧", name: "penguin", category: "Animals", keywords: ["penguin"] },
  { char: "🐦", name: "bird", category: "Animals", keywords: ["bird"] },
  { char: "🦆", name: "duck", category: "Animals", keywords: ["duck"] },
  { char: "🦅", name: "eagle", category: "Animals", keywords: ["eagle", "bird"] },
  { char: "🦉", name: "owl", category: "Animals", keywords: ["owl", "wise"] },
  { char: "🦋", name: "butterfly", category: "Animals", keywords: ["butterfly", "insect"] },
  { char: "🐛", name: "bug", category: "Animals", keywords: ["bug", "caterpillar"] },
  { char: "🐝", name: "honeybee", category: "Animals", keywords: ["bee", "honey"] },
  { char: "🐞", name: "lady beetle", category: "Animals", keywords: ["ladybug", "ladybird"] },
  { char: "🐢", name: "turtle", category: "Animals", keywords: ["turtle", "slow"] },
  { char: "🐍", name: "snake", category: "Animals", keywords: ["snake"] },
  { char: "🦎", name: "lizard", category: "Animals", keywords: ["lizard", "reptile"] },
  { char: "🐊", name: "crocodile", category: "Animals", keywords: ["crocodile", "alligator"] },
  { char: "🐠", name: "tropical fish", category: "Animals", keywords: ["fish", "tropical"] },
  { char: "🐟", name: "fish", category: "Animals", keywords: ["fish"] },
  { char: "🐡", name: "blowfish", category: "Animals", keywords: ["fish", "blowfish"] },
  { char: "🐬", name: "dolphin", category: "Animals", keywords: ["dolphin"] },
  { char: "🦈", name: "shark", category: "Animals", keywords: ["shark"] },
  { char: "🐳", name: "spouting whale", category: "Animals", keywords: ["whale"] },
  { char: "🐙", name: "octopus", category: "Animals", keywords: ["octopus"] },
  { char: "🦑", name: "squid", category: "Animals", keywords: ["squid"] },
  { char: "🦐", name: "shrimp", category: "Animals", keywords: ["shrimp"] },
  { char: "🦞", name: "lobster", category: "Animals", keywords: ["lobster"] },
  { char: "🦀", name: "crab", category: "Animals", keywords: ["crab"] },
  { char: "🐘", name: "elephant", category: "Animals", keywords: ["elephant"] },
  { char: "🦏", name: "rhinoceros", category: "Animals", keywords: ["rhino"] },
  { char: "🦛", name: "hippopotamus", category: "Animals", keywords: ["hippo"] },
  { char: "🐪", name: "camel", category: "Animals", keywords: ["camel", "desert"] },
  { char: "🦒", name: "giraffe", category: "Animals", keywords: ["giraffe"] },
  { char: "🦘", name: "kangaroo", category: "Animals", keywords: ["kangaroo", "australia"] },
  { char: "🐃", name: "water buffalo", category: "Animals", keywords: ["buffalo"] },
  { char: "🐄", name: "cow", category: "Animals", keywords: ["cow"] },
  { char: "🐎", name: "horse", category: "Animals", keywords: ["horse"] },
  { char: "🐖", name: "pig", category: "Animals", keywords: ["pig"] },
  { char: "🐏", name: "ram", category: "Animals", keywords: ["sheep", "ram"] },
  { char: "🦙", name: "llama", category: "Animals", keywords: ["llama", "alpaca"] },
  { char: "🐐", name: "goat", category: "Animals", keywords: ["goat"] },
  { char: "🦌", name: "deer", category: "Animals", keywords: ["deer"] },
  { char: "🐕", name: "dog", category: "Animals", keywords: ["dog"] },
  { char: "🐩", name: "poodle", category: "Animals", keywords: ["poodle", "dog"] },
  { char: "🦮", name: "guide dog", category: "Animals", keywords: ["dog", "guide"] },
  { char: "🐈", name: "cat", category: "Animals", keywords: ["cat"] },
  { char: "🐓", name: "rooster", category: "Animals", keywords: ["rooster", "cock"] },
  // Food
  { char: "🍎", name: "red apple", category: "Food", keywords: ["apple", "fruit"] },
  { char: "🍊", name: "tangerine", category: "Food", keywords: ["orange", "tangerine", "fruit"] },
  { char: "🍋", name: "lemon", category: "Food", keywords: ["lemon", "sour"] },
  { char: "🍇", name: "grapes", category: "Food", keywords: ["grapes", "fruit"] },
  { char: "🍓", name: "strawberry", category: "Food", keywords: ["strawberry", "fruit"] },
  { char: "🍒", name: "cherries", category: "Food", keywords: ["cherry", "fruit"] },
  { char: "🍑", name: "peach", category: "Food", keywords: ["peach", "fruit"] },
  { char: "🍍", name: "pineapple", category: "Food", keywords: ["pineapple", "tropical"] },
  { char: "🥭", name: "mango", category: "Food", keywords: ["mango", "tropical"] },
  { char: "🍌", name: "banana", category: "Food", keywords: ["banana", "fruit"] },
  { char: "🍉", name: "watermelon", category: "Food", keywords: ["watermelon", "fruit"] },
  { char: "🍈", name: "melon", category: "Food", keywords: ["melon", "fruit"] },
  { char: "🍏", name: "green apple", category: "Food", keywords: ["apple", "green"] },
  { char: "🍐", name: "pear", category: "Food", keywords: ["pear", "fruit"] },
  { char: "🥥", name: "coconut", category: "Food", keywords: ["coconut", "tropical"] },
  { char: "🥝", name: "kiwi fruit", category: "Food", keywords: ["kiwi", "fruit"] },
  { char: "🍅", name: "tomato", category: "Food", keywords: ["tomato"] },
  { char: "🥑", name: "avocado", category: "Food", keywords: ["avocado", "guac"] },
  { char: "🥕", name: "carrot", category: "Food", keywords: ["carrot", "vegetable"] },
  { char: "🌽", name: "ear of corn", category: "Food", keywords: ["corn", "maize"] },
  { char: "🍕", name: "pizza", category: "Food", keywords: ["pizza", "italian"] },
  { char: "🍔", name: "hamburger", category: "Food", keywords: ["burger", "hamburger"] },
  { char: "🍟", name: "french fries", category: "Food", keywords: ["fries", "chips"] },
  { char: "🌮", name: "taco", category: "Food", keywords: ["taco", "mexican"] },
  { char: "🌯", name: "burrito", category: "Food", keywords: ["burrito", "mexican"] },
  { char: "🍜", name: "steaming bowl", category: "Food", keywords: ["noodles", "ramen"] },
  { char: "🍝", name: "spaghetti", category: "Food", keywords: ["pasta", "spaghetti"] },
  { char: "🍣", name: "sushi", category: "Food", keywords: ["sushi", "japanese"] },
  { char: "🍱", name: "bento box", category: "Food", keywords: ["bento", "japanese"] },
  { char: "🍛", name: "curry rice", category: "Food", keywords: ["curry", "indian"] },
  { char: "🍲", name: "pot of food", category: "Food", keywords: ["stew", "soup"] },
  { char: "🥗", name: "green salad", category: "Food", keywords: ["salad", "healthy"] },
  { char: "🥞", name: "pancakes", category: "Food", keywords: ["pancakes", "breakfast"] },
  { char: "🧇", name: "waffle", category: "Food", keywords: ["waffle", "breakfast"] },
  { char: "🍰", name: "shortcake", category: "Food", keywords: ["cake", "dessert"] },
  { char: "🎂", name: "birthday cake", category: "Food", keywords: ["cake", "birthday"] },
  { char: "🧁", name: "cupcake", category: "Food", keywords: ["cupcake", "dessert"] },
  { char: "🍩", name: "doughnut", category: "Food", keywords: ["donut", "doughnut"] },
  { char: "🍪", name: "cookie", category: "Food", keywords: ["cookie", "biscuit"] },
  { char: "🍫", name: "chocolate bar", category: "Food", keywords: ["chocolate", "candy"] },
  { char: "🍬", name: "candy", category: "Food", keywords: ["candy", "sweet"] },
  { char: "🍭", name: "lollipop", category: "Food", keywords: ["lollipop", "candy"] },
  { char: "☕", name: "hot beverage", category: "Food", keywords: ["coffee", "tea", "hot"] },
  { char: "🍵", name: "teacup without handle", category: "Food", keywords: ["tea", "green tea"] },
  { char: "🧃", name: "beverage box", category: "Food", keywords: ["juice", "drink"] },
  { char: "🥤", name: "cup with straw", category: "Food", keywords: ["soda", "drink"] },
  { char: "🍺", name: "beer mug", category: "Food", keywords: ["beer", "drink"] },
  { char: "🍷", name: "wine glass", category: "Food", keywords: ["wine", "drink"] },
  { char: "🍸", name: "cocktail glass", category: "Food", keywords: ["cocktail", "drink"] },
  { char: "🥂", name: "clinking glasses", category: "Food", keywords: ["toast", "celebrate", "cheers"] },
  // Travel
  { char: "🚗", name: "automobile", category: "Travel", keywords: ["car", "drive"] },
  { char: "🚕", name: "taxi", category: "Travel", keywords: ["taxi", "cab"] },
  { char: "🚌", name: "bus", category: "Travel", keywords: ["bus", "transit"] },
  { char: "🚎", name: "trolleybus", category: "Travel", keywords: ["trolley", "bus"] },
  { char: "🏎️", name: "racing car", category: "Travel", keywords: ["race car", "fast"] },
  { char: "🚓", name: "police car", category: "Travel", keywords: ["police", "cop"] },
  { char: "🚑", name: "ambulance", category: "Travel", keywords: ["ambulance", "emergency"] },
  { char: "🚒", name: "fire engine", category: "Travel", keywords: ["fire truck", "fire"] },
  { char: "🚐", name: "minibus", category: "Travel", keywords: ["van", "bus"] },
  { char: "🚚", name: "delivery truck", category: "Travel", keywords: ["truck", "delivery"] },
  { char: "🛻", name: "pickup truck", category: "Travel", keywords: ["pickup", "truck"] },
  { char: "✈️", name: "airplane", category: "Travel", keywords: ["plane", "fly", "airport"] },
  { char: "🚀", name: "rocket", category: "Travel", keywords: ["rocket", "space"] },
  { char: "🛸", name: "flying saucer", category: "Travel", keywords: ["ufo", "alien"] },
  { char: "🚁", name: "helicopter", category: "Travel", keywords: ["helicopter", "fly"] },
  { char: "⛵", name: "sailboat", category: "Travel", keywords: ["boat", "sail", "sea"] },
  { char: "🚢", name: "ship", category: "Travel", keywords: ["ship", "cruise", "boat"] },
  { char: "🌍", name: "globe showing Europe-Africa", category: "Travel", keywords: ["world", "earth", "globe"] },
  { char: "🗺️", name: "world map", category: "Travel", keywords: ["map", "world"] },
  { char: "🏔️", name: "snow-capped mountain", category: "Travel", keywords: ["mountain", "snow"] },
  { char: "🏖️", name: "beach with umbrella", category: "Travel", keywords: ["beach", "summer"] },
  { char: "🏕️", name: "camping", category: "Travel", keywords: ["camping", "tent"] },
  { char: "🗼", name: "Tokyo tower", category: "Travel", keywords: ["tokyo", "japan"] },
  { char: "🗽", name: "Statue of Liberty", category: "Travel", keywords: ["liberty", "usa", "new york"] },
  { char: "🏰", name: "European castle", category: "Travel", keywords: ["castle", "europe"] },
  // Activities
  { char: "⚽", name: "soccer ball", category: "Activities", keywords: ["soccer", "football"] },
  { char: "🏀", name: "basketball", category: "Activities", keywords: ["basketball"] },
  { char: "🏈", name: "american football", category: "Activities", keywords: ["football", "american"] },
  { char: "⚾", name: "baseball", category: "Activities", keywords: ["baseball"] },
  { char: "🎾", name: "tennis", category: "Activities", keywords: ["tennis"] },
  { char: "🏐", name: "volleyball", category: "Activities", keywords: ["volleyball"] },
  { char: "🎮", name: "video game", category: "Activities", keywords: ["game", "controller", "gaming"] },
  { char: "🕹️", name: "joystick", category: "Activities", keywords: ["joystick", "game", "arcade"] },
  { char: "🎲", name: "game die", category: "Activities", keywords: ["dice", "random", "game"] },
  { char: "♟️", name: "chess pawn", category: "Activities", keywords: ["chess", "game"] },
  { char: "🎨", name: "artist palette", category: "Activities", keywords: ["art", "paint", "palette"] },
  { char: "🎭", name: "performing arts", category: "Activities", keywords: ["theater", "drama"] },
  { char: "🎪", name: "circus tent", category: "Activities", keywords: ["circus", "tent"] },
  { char: "🎵", name: "musical note", category: "Activities", keywords: ["music", "note"] },
  { char: "🎶", name: "musical notes", category: "Activities", keywords: ["music", "notes"] },
  { char: "🎸", name: "guitar", category: "Activities", keywords: ["guitar", "music"] },
  { char: "🎹", name: "musical keyboard", category: "Activities", keywords: ["piano", "keyboard"] },
  { char: "🥁", name: "drum", category: "Activities", keywords: ["drum", "music"] },
  { char: "🎤", name: "microphone", category: "Activities", keywords: ["microphone", "sing"] },
  { char: "🎧", name: "headphone", category: "Activities", keywords: ["headphones", "music"] },
  { char: "📚", name: "books", category: "Activities", keywords: ["books", "read", "study"] },
  { char: "✏️", name: "pencil", category: "Activities", keywords: ["pencil", "write"] },
  // Objects
  { char: "💻", name: "laptop", category: "Objects", keywords: ["laptop", "computer", "mac"] },
  { char: "🖥️", name: "desktop computer", category: "Objects", keywords: ["computer", "desktop", "pc"] },
  { char: "📱", name: "mobile phone", category: "Objects", keywords: ["phone", "mobile", "smartphone"] },
  { char: "⌨️", name: "keyboard", category: "Objects", keywords: ["keyboard", "type"] },
  { char: "🖱️", name: "computer mouse", category: "Objects", keywords: ["mouse", "cursor"] },
  { char: "💡", name: "light bulb", category: "Objects", keywords: ["idea", "light", "bulb"] },
  { char: "🔋", name: "battery", category: "Objects", keywords: ["battery", "power"] },
  { char: "🔌", name: "electric plug", category: "Objects", keywords: ["plug", "power", "charger"] },
  { char: "📷", name: "camera", category: "Objects", keywords: ["camera", "photo"] },
  { char: "🎥", name: "movie camera", category: "Objects", keywords: ["camera", "video", "movie"] },
  { char: "📺", name: "television", category: "Objects", keywords: ["tv", "television"] },
  { char: "📻", name: "radio", category: "Objects", keywords: ["radio"] },
  { char: "📞", name: "telephone receiver", category: "Objects", keywords: ["phone", "call"] },
  { char: "🔑", name: "key", category: "Objects", keywords: ["key", "lock"] },
  { char: "🔒", name: "locked", category: "Objects", keywords: ["lock", "secure"] },
  { char: "🔓", name: "unlocked", category: "Objects", keywords: ["unlock", "open"] },
  { char: "⚙️", name: "gear", category: "Objects", keywords: ["settings", "gear", "cog"] },
  { char: "🔧", name: "wrench", category: "Objects", keywords: ["wrench", "tool", "fix"] },
  { char: "🔨", name: "hammer", category: "Objects", keywords: ["hammer", "tool", "build"] },
  { char: "💣", name: "bomb", category: "Objects", keywords: ["bomb", "explosion"] },
  { char: "🧲", name: "magnet", category: "Objects", keywords: ["magnet", "attract"] },
  { char: "🪄", name: "magic wand", category: "Objects", keywords: ["magic", "wand"] },
  { char: "🎁", name: "wrapped gift", category: "Objects", keywords: ["gift", "present", "birthday"] },
  { char: "🎀", name: "ribbon", category: "Objects", keywords: ["ribbon", "bow"] },
  { char: "🏆", name: "trophy", category: "Objects", keywords: ["trophy", "award", "winner"] },
  { char: "🥇", name: "1st place medal", category: "Objects", keywords: ["gold", "medal", "first"] },
  { char: "💰", name: "money bag", category: "Objects", keywords: ["money", "rich", "bag"] },
  { char: "💎", name: "gem stone", category: "Objects", keywords: ["diamond", "gem", "crystal"] },
  // Symbols
  { char: "❤️", name: "red heart", category: "Symbols", keywords: ["heart", "love", "red"] },
  { char: "🧡", name: "orange heart", category: "Symbols", keywords: ["heart", "orange"] },
  { char: "💛", name: "yellow heart", category: "Symbols", keywords: ["heart", "yellow"] },
  { char: "💚", name: "green heart", category: "Symbols", keywords: ["heart", "green"] },
  { char: "💙", name: "blue heart", category: "Symbols", keywords: ["heart", "blue"] },
  { char: "💜", name: "purple heart", category: "Symbols", keywords: ["heart", "purple"] },
  { char: "🖤", name: "black heart", category: "Symbols", keywords: ["heart", "black"] },
  { char: "💔", name: "broken heart", category: "Symbols", keywords: ["broken", "heartbreak"] },
  { char: "✨", name: "sparkles", category: "Symbols", keywords: ["sparkle", "shiny", "stars"] },
  { char: "⭐", name: "star", category: "Symbols", keywords: ["star", "favorite"] },
  { char: "🌟", name: "glowing star", category: "Symbols", keywords: ["star", "gold"] },
  { char: "💥", name: "collision", category: "Symbols", keywords: ["boom", "explosion"] },
  { char: "🔥", name: "fire", category: "Symbols", keywords: ["fire", "hot", "lit"] },
  { char: "🌈", name: "rainbow", category: "Symbols", keywords: ["rainbow", "colors"] },
  { char: "☀️", name: "sun", category: "Symbols", keywords: ["sun", "sunny", "hot"] },
  { char: "🌙", name: "crescent moon", category: "Symbols", keywords: ["moon", "night"] },
  { char: "⚡", name: "high voltage", category: "Symbols", keywords: ["lightning", "electric", "fast"] },
  { char: "❄️", name: "snowflake", category: "Symbols", keywords: ["snow", "cold", "winter"] },
  { char: "💧", name: "droplet", category: "Symbols", keywords: ["water", "drop"] },
  { char: "🌊", name: "water wave", category: "Symbols", keywords: ["wave", "ocean", "sea"] },
  { char: "✅", name: "check mark button", category: "Symbols", keywords: ["check", "yes", "done"] },
  { char: "❌", name: "cross mark", category: "Symbols", keywords: ["no", "wrong", "x"] },
  { char: "‼️", name: "double exclamation mark", category: "Symbols", keywords: ["exclamation", "important"] },
  { char: "❓", name: "question mark", category: "Symbols", keywords: ["question", "?"] },
  { char: "💯", name: "hundred points", category: "Symbols", keywords: ["100", "perfect", "score"] },
  { char: "🔴", name: "red circle", category: "Symbols", keywords: ["red", "circle"] },
  { char: "🟠", name: "orange circle", category: "Symbols", keywords: ["orange", "circle"] },
  { char: "🟡", name: "yellow circle", category: "Symbols", keywords: ["yellow", "circle"] },
  { char: "🟢", name: "green circle", category: "Symbols", keywords: ["green", "circle"] },
  { char: "🔵", name: "blue circle", category: "Symbols", keywords: ["blue", "circle"] },
  { char: "🟣", name: "purple circle", category: "Symbols", keywords: ["purple", "circle"] },
  { char: "⬛", name: "black large square", category: "Symbols", keywords: ["black", "square"] },
  { char: "⬜", name: "white large square", category: "Symbols", keywords: ["white", "square"] },
  // Flags
  { char: "🏳️", name: "white flag", category: "Flags", keywords: ["white flag", "surrender"] },
  { char: "🏴", name: "black flag", category: "Flags", keywords: ["black flag", "pirate"] },
  { char: "🚩", name: "triangular flag", category: "Flags", keywords: ["flag", "red flag", "warning"] },
  { char: "🏁", name: "chequered flag", category: "Flags", keywords: ["race", "finish", "checkered"] },
  { char: "🇺🇸", name: "flag United States", category: "Flags", keywords: ["usa", "america", "us"] },
  { char: "🇬🇧", name: "flag United Kingdom", category: "Flags", keywords: ["uk", "britain", "england"] },
  { char: "🇨🇦", name: "flag Canada", category: "Flags", keywords: ["canada", "maple leaf"] },
  { char: "🇦🇺", name: "flag Australia", category: "Flags", keywords: ["australia"] },
  { char: "🇩🇪", name: "flag Germany", category: "Flags", keywords: ["germany", "german"] },
  { char: "🇫🇷", name: "flag France", category: "Flags", keywords: ["france", "french"] },
  { char: "🇯🇵", name: "flag Japan", category: "Flags", keywords: ["japan", "japanese"] },
  { char: "🇨🇳", name: "flag China", category: "Flags", keywords: ["china", "chinese"] },
  { char: "🇧🇷", name: "flag Brazil", category: "Flags", keywords: ["brazil", "brazil"] },
  { char: "🇮🇳", name: "flag India", category: "Flags", keywords: ["india", "indian"] },
  { char: "🇲🇽", name: "flag Mexico", category: "Flags", keywords: ["mexico", "mexican"] },
  { char: "🇰🇷", name: "flag South Korea", category: "Flags", keywords: ["korea", "korean"] },
];
