export type ToolStatus = "planned" | "live" | "beta" | "deprecated" | "featured";
export type DependencyWeight = "light" | "medium" | "heavy" | "massive";

export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  status: ToolStatus;
  dependencies?: DependencyWeight;
  related?: string[];
  isNew?: boolean;
}

export const tools: Tool[] = [
  // ─── Text & Language ───────────────────────────────────────────────
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description:
      "Count words, characters, sentences, paragraphs with readability scores",
    category: "text",
    tags: ["word count", "character count", "readability", "flesch-kincaid"],
    status: "live",
    dependencies: "light",
    related: ["reading-time", "text-similarity", "word-frequency"],
  },
  {
    slug: "markdown-editor",
    name: "Markdown Editor",
    description: "Live split-pane editor with instant HTML preview and export",
    category: "text",
    tags: ["markdown", "editor", "html", "preview", "writing"],
    status: "live",
    dependencies: "medium",
    related: ["markdown-to-html", "markdown-table", "word-counter"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description:
      "Generate placeholder text in multiple styles (classic, hipster, corporate)",
    category: "text",
    tags: ["lorem ipsum", "placeholder", "dummy text", "filler"],
    status: "live",
    dependencies: "light",
    related: ["word-counter", "slug-generator", "name-generator"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description:
      "Transform text between camelCase, snake_case, PascalCase, Title Case, UPPER, lower, kebab-case",
    category: "text",
    tags: [
      "case",
      "camelCase",
      "snake_case",
      "PascalCase",
      "title case",
      "uppercase",
      "lowercase",
      "kebab-case",
    ],
    status: "live",
    dependencies: "light",
    related: ["slug-generator", "string-escaper", "word-counter"],
  },
  {
    slug: "text-diff",
    name: "Text Diff Tool",
    description:
      "Side-by-side comparison with highlighted additions, deletions, and changes",
    category: "text",
    tags: ["diff", "compare", "text comparison", "changes"],
    status: "planned",
    dependencies: "medium",
    related: ["diff-viewer", "text-similarity", "word-counter"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description:
      "Test regular expressions with real-time match highlighting, capture groups, and cheat sheet",
    category: "text",
    tags: [
      "regex",
      "regular expression",
      "pattern matching",
      "regexp",
      "test",
    ],
    status: "featured",
    dependencies: "light",
    related: ["string-escaper", "text-diff", "slug-generator"],
  },
  {
    slug: "morse-code",
    name: "Morse Code Translator",
    description: "Encode/decode Morse code with audio playback via Web Audio API",
    category: "text",
    tags: ["morse code", "encode", "decode", "audio", "translator"],
    status: "planned",
    dependencies: "light",
    related: ["base64", "url-encoder", "binary-teacher"],
  },
  {
    slug: "word-frequency",
    name: "Word Frequency Analyzer",
    description:
      "Visualize most-used words in text — useful for SEO and writing",
    category: "text",
    tags: ["word frequency", "SEO", "analysis", "text analysis"],
    status: "planned",
    dependencies: "light",
    related: ["word-counter", "text-similarity", "reading-time"],
  },
  {
    slug: "text-similarity",
    name: "Text Similarity Checker",
    description:
      "Compare two texts using cosine similarity to detect overlap",
    category: "text",
    tags: ["similarity", "cosine", "compare", "overlap", "plagiarism"],
    status: "planned",
    dependencies: "light",
    related: ["text-diff", "word-frequency", "word-counter"],
  },
  {
    slug: "name-generator",
    name: "Name & Username Generator",
    description:
      "Random name generator with filters for style, length, and theme",
    category: "text",
    tags: ["name", "username", "generator", "random", "fantasy"],
    status: "planned",
    dependencies: "light",
    related: ["password-generator", "uuid-generator", "lorem-ipsum"],
  },
  {
    slug: "text-to-speech",
    name: "Text-to-Speech Previewer",
    description:
      "Preview text in browser voices and speeds using SpeechSynthesis API",
    category: "text",
    tags: ["text to speech", "TTS", "voice", "speech", "audio"],
    status: "planned",
    dependencies: "light",
    related: ["morse-code", "word-counter", "reading-time"],
  },
  {
    slug: "transliteration",
    name: "Transliteration Tool",
    description: "Convert between writing systems — Latin ↔ Cyrillic",
    category: "text",
    tags: ["transliteration", "cyrillic", "latin", "writing system"],
    status: "planned",
    dependencies: "light",
    related: ["unicode-lookup", "morse-code", "case-converter"],
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Turn any title into a URL-friendly slug",
    category: "text",
    tags: ["slug", "URL", "permalink", "SEO", "URL-friendly"],
    status: "live",
    dependencies: "light",
    related: ["url-encoder", "case-converter", "string-escaper"],
  },
  {
    slug: "string-escaper",
    name: "String Escaper/Unescaper",
    description: "Escape and unescape for HTML, JSON, URL, XML, CSV",
    category: "text",
    tags: ["escape", "unescape", "HTML", "JSON", "URL", "XML", "CSV"],
    status: "live",
    dependencies: "light",
    related: ["html-entities", "url-encoder", "slug-generator"],
  },
  {
    slug: "whitespace-cleaner",
    name: "Whitespace Cleaner",
    description:
      "Strip trailing spaces, normalize line endings, remove invisible Unicode",
    category: "text",
    tags: [
      "whitespace",
      "trim",
      "clean",
      "line endings",
      "invisible characters",
    ],
    status: "live",
    dependencies: "light",
    related: ["text-cleaner", "unicode-lookup", "case-converter"],
  },
  {
    slug: "reverse-text",
    name: "Reverse Text / Mirror",
    description:
      "Reverse, flip, or mirror text — character-level or word-level",
    category: "text",
    tags: ["reverse", "flip", "mirror", "backwards", "upside down"],
    status: "live",
    dependencies: "light",
    related: ["case-converter", "zalgo-text", "unicode-lookup"],
  },
  {
    slug: "unicode-lookup",
    name: "Unicode Character Lookup",
    description:
      "Search, browse, and copy Unicode symbols, emojis, and special characters",
    category: "text",
    tags: ["unicode", "emoji", "symbols", "special characters", "codepoint"],
    status: "planned",
    dependencies: "light",
    related: ["emoji-search", "transliteration", "whitespace-cleaner"],
  },
  {
    slug: "zalgo-text",
    name: "Zalgo Text Generator",
    description: "Add combining characters to text for stylistic/meme use",
    category: "text",
    tags: ["zalgo", "glitch", "meme", "combining characters", "creepy text"],
    status: "planned",
    dependencies: "light",
    related: ["reverse-text", "unicode-lookup", "name-generator"],
  },

  // ─── Developer Tools ───────────────────────────────────────────────
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Pretty-print, validate, minify, and view JSON as a collapsible tree",
    category: "developer",
    tags: [
      "JSON",
      "format",
      "validate",
      "minify",
      "pretty print",
      "tree view",
    ],
    status: "featured",
    dependencies: "light",
    related: ["yaml-json", "csv-json", "xml-json"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode text or files to/from Base64",
    category: "developer",
    tags: ["base64", "encode", "decode", "binary", "data URI"],
    status: "live",
    dependencies: "light",
    related: ["url-encoder", "hash-generator", "image-to-base64"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Percent-encode and decode URL components",
    category: "developer",
    tags: ["URL", "encode", "decode", "percent encoding", "URI"],
    status: "live",
    dependencies: "light",
    related: ["base64", "html-entities", "slug-generator"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description:
      "Paste a JWT and see decoded header, payload, and expiration",
    category: "developer",
    tags: ["JWT", "JSON Web Token", "decode", "token", "auth"],
    status: "live",
    dependencies: "light",
    related: ["jwt-builder", "base64", "json-formatter"],
  },
  {
    slug: "jwt-builder",
    name: "JWT Builder",
    description: "Craft and sign JWTs with a user-provided secret",
    category: "developer",
    tags: ["JWT", "JSON Web Token", "sign", "create", "HMAC"],
    status: "planned",
    dependencies: "light",
    related: ["jwt-decoder", "hmac-generator", "base64"],
  },
  {
    slug: "uuid-generator",
    name: "UUID / ULID Generator",
    description: "Generate v4 UUIDs, ULIDs, nanoids — bulk and copy",
    category: "developer",
    tags: ["UUID", "ULID", "nanoid", "unique ID", "generator"],
    status: "live",
    dependencies: "light",
    related: ["password-generator", "random-generator", "random-bytes"],
  },
  {
    slug: "cron-builder",
    name: "Cron Expression Builder",
    description:
      "Visual cron schedule builder with human-readable descriptions and next-run preview",
    category: "developer",
    tags: ["cron", "schedule", "crontab", "recurring", "timer"],
    status: "live",
    dependencies: "light",
    related: ["timestamp-converter", "epoch-countdown", "date-difference"],
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode/decode HTML entities — named and numeric",
    category: "developer",
    tags: ["HTML", "entity", "encode", "decode", "ampersand"],
    status: "live",
    dependencies: "light",
    related: ["string-escaper", "url-encoder", "base64"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Beautify and indent raw SQL queries",
    category: "developer",
    tags: ["SQL", "format", "beautify", "query", "indent"],
    status: "planned",
    dependencies: "medium",
    related: ["json-formatter", "yaml-json", "csv-json"],
  },
  {
    slug: "flexbox-playground",
    name: "CSS Flexbox Playground",
    description:
      "Toggle every flex property and see layout changes in real time",
    category: "developer",
    tags: ["CSS", "flexbox", "layout", "flex", "playground"],
    status: "planned",
    dependencies: "light",
    related: ["grid-playground", "box-shadow", "animation-builder"],
  },
  {
    slug: "grid-playground",
    name: "CSS Grid Playground",
    description:
      "Visual grid builder — define rows, columns, gaps, place items",
    category: "developer",
    tags: ["CSS", "grid", "layout", "columns", "rows", "playground"],
    status: "planned",
    dependencies: "light",
    related: ["flexbox-playground", "box-shadow", "animation-builder"],
  },
  {
    slug: "og-preview",
    name: "Open Graph Previewer",
    description: "Paste HTML meta tags and preview social cards",
    category: "developer",
    tags: [
      "Open Graph",
      "OG",
      "social card",
      "meta tags",
      "Twitter card",
      "preview",
    ],
    status: "planned",
    dependencies: "light",
    related: ["html-entities", "json-formatter", "breakpoint-tester"],
  },
  {
    slug: "breakpoint-tester",
    name: "Responsive Breakpoint Tester",
    description: "Preview a URL at common device widths",
    category: "developer",
    tags: ["responsive", "breakpoint", "device", "preview", "viewport"],
    status: "planned",
    dependencies: "light",
    related: ["og-preview", "flexbox-playground", "grid-playground"],
  },
  {
    slug: "snippet-manager",
    name: "Snippet Manager",
    description: "Save, tag, and search code snippets in localStorage",
    category: "developer",
    tags: [
      "snippet",
      "code",
      "save",
      "manager",
      "syntax highlighting",
      "gist",
    ],
    status: "planned",
    dependencies: "medium",
    related: ["json-formatter", "notepad", "markdown-editor"],
  },
  {
    slug: "api-mocker",
    name: "API Response Mocker",
    description: "Define mock endpoints and responses for frontend dev",
    category: "developer",
    tags: ["API", "mock", "endpoint", "response", "REST", "frontend"],
    status: "planned",
    dependencies: "light",
    related: ["json-formatter", "http-status-codes", "jwt-decoder"],
  },
  {
    slug: "diff-viewer",
    name: "Diff / Patch Viewer",
    description: "Visualize unified diffs with syntax highlighting",
    category: "developer",
    tags: ["diff", "patch", "unified diff", "code review", "changes"],
    status: "planned",
    dependencies: "light",
    related: ["text-diff", "json-formatter", "snippet-manager"],
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description:
      "Convert between Unix epoch, ISO 8601, RFC 2822, and human-readable",
    category: "developer",
    tags: [
      "timestamp",
      "Unix",
      "epoch",
      "ISO 8601",
      "RFC 2822",
      "date",
      "time",
    ],
    status: "live",
    dependencies: "light",
    related: ["epoch-countdown", "date-difference", "timezone-converter"],
  },
  {
    slug: "yaml-json",
    name: "YAML ↔ JSON Converter",
    description: "Convert between YAML and JSON",
    category: "developer",
    tags: ["YAML", "JSON", "convert", "config", "data format"],
    status: "planned",
    dependencies: "medium",
    related: ["json-formatter", "toml-json", "csv-json"],
  },
  {
    slug: "csv-json",
    name: "CSV ↔ JSON Converter",
    description: "Transform CSV to JSON array and vice versa",
    category: "developer",
    tags: ["CSV", "JSON", "convert", "data", "table", "spreadsheet"],
    status: "planned",
    dependencies: "medium",
    related: ["json-formatter", "json-to-csv", "yaml-json"],
  },
  {
    slug: "xml-json",
    name: "XML ↔ JSON Converter",
    description: "Bidirectional XML and JSON conversion",
    category: "developer",
    tags: ["XML", "JSON", "convert", "data format", "markup"],
    status: "planned",
    dependencies: "light",
    related: ["json-formatter", "yaml-json", "html-entities"],
  },
  {
    slug: "toml-json",
    name: "TOML ↔ JSON Converter",
    description: "Parse and convert TOML configuration files",
    category: "developer",
    tags: ["TOML", "JSON", "convert", "config", "configuration"],
    status: "planned",
    dependencies: "medium",
    related: ["yaml-json", "json-formatter", "csv-json"],
  },
  {
    slug: "http-status-codes",
    name: "HTTP Status Code Reference",
    description: "Searchable reference of all status codes",
    category: "developer",
    tags: [
      "HTTP",
      "status code",
      "reference",
      "200",
      "404",
      "500",
      "REST",
    ],
    status: "planned",
    dependencies: "light",
    related: ["api-mocker", "dns-reference", "port-reference"],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Visual permission calculator for Unix file permissions",
    category: "developer",
    tags: ["chmod", "permissions", "Unix", "Linux", "file permissions", "octal"],
    status: "live",
    dependencies: "light",
    related: ["number-base-converter", "bitwise-visualizer", "subnet-calculator"],
  },
  {
    slug: "user-agent-parser",
    name: "User-Agent Parser",
    description:
      "Parse a user-agent string into browser, OS, device details",
    category: "developer",
    tags: ["user-agent", "browser", "OS", "device", "parser"],
    status: "planned",
    dependencies: "light",
    related: ["http-status-codes", "jwt-decoder", "og-preview"],
  },
  {
    slug: "markdown-table",
    name: "Markdown Table Generator",
    description: "Visual table editor that outputs Markdown or HTML",
    category: "developer",
    tags: ["markdown", "table", "generator", "HTML", "editor"],
    status: "planned",
    dependencies: "light",
    related: ["markdown-editor", "csv-json", "json-formatter"],
  },
  {
    slug: "epoch-countdown",
    name: "Epoch Countdown",
    description: "Live ticking Unix timestamp with conversion",
    category: "developer",
    tags: ["epoch", "Unix timestamp", "live", "countdown", "time"],
    status: "live",
    dependencies: "light",
    related: ["timestamp-converter", "countdown", "date-difference"],
  },

  // ─── Color & Design ────────────────────────────────────────────────
  {
    slug: "color-picker",
    name: "Color Picker & Converter",
    description:
      "Pick colors and convert between HEX, RGB, HSL, HSB, CMYK",
    category: "design",
    tags: ["color", "picker", "HEX", "RGB", "HSL", "HSB", "CMYK", "converter"],
    status: "featured",
    dependencies: "light",
    related: ["gradient-generator", "contrast-checker", "palette-generator"],
  },
  {
    slug: "gradient-generator",
    name: "CSS Gradient Generator",
    description:
      "Build linear, radial, and conic gradients with visual stops",
    category: "design",
    tags: ["CSS", "gradient", "linear", "radial", "conic", "generator"],
    status: "live",
    dependencies: "light",
    related: ["color-picker", "glassmorphism", "box-shadow"],
  },
  {
    slug: "contrast-checker",
    name: "Contrast Ratio Checker",
    description: "Check color pairs against WCAG AA/AAA",
    category: "design",
    tags: [
      "contrast",
      "WCAG",
      "accessibility",
      "AA",
      "AAA",
      "color ratio",
    ],
    status: "live",
    dependencies: "light",
    related: ["color-picker", "palette-generator", "color-blind-sim"],
  },
  {
    slug: "palette-generator",
    name: "Color Palette Generator",
    description:
      "Generate harmonious palettes — complementary, analogous, triadic",
    category: "design",
    tags: [
      "palette",
      "color",
      "harmony",
      "complementary",
      "analogous",
      "triadic",
    ],
    status: "planned",
    dependencies: "light",
    related: ["color-picker", "contrast-checker", "tailwind-colors"],
  },
  {
    slug: "palette-extractor",
    name: "Color Palette Extractor",
    description: "Upload an image and extract dominant colors",
    category: "design",
    tags: ["palette", "extract", "image", "dominant colors", "color picker"],
    status: "planned",
    dependencies: "light",
    related: ["color-picker", "palette-generator", "image-resizer"],
  },
  {
    slug: "duotone-filter",
    name: "Duotone Image Filter",
    description: "Apply duotone color effects using Canvas API",
    category: "design",
    tags: ["duotone", "filter", "image", "canvas", "effect"],
    status: "planned",
    dependencies: "light",
    related: ["color-picker", "palette-extractor", "image-resizer"],
  },
  {
    slug: "font-pairing",
    name: "Font Pairing Previewer",
    description: "Browse and preview Google Font combinations",
    category: "design",
    tags: ["font", "pairing", "Google Fonts", "typography", "preview"],
    status: "planned",
    dependencies: "light",
    related: ["type-scale", "glassmorphism", "neumorphism"],
  },
  {
    slug: "box-shadow",
    name: "Box Shadow Generator",
    description: "Visual CSS box-shadow builder with multiple layers",
    category: "design",
    tags: ["CSS", "box-shadow", "shadow", "generator", "layers"],
    status: "planned",
    dependencies: "light",
    related: ["border-radius", "glassmorphism", "neumorphism"],
  },
  {
    slug: "border-radius",
    name: "Border Radius Previewer",
    description: "Drag corners to create complex border-radius values",
    category: "design",
    tags: ["CSS", "border-radius", "rounded", "corners", "generator"],
    status: "planned",
    dependencies: "light",
    related: ["box-shadow", "glassmorphism", "neumorphism"],
  },
  {
    slug: "animation-builder",
    name: "CSS Animation Builder",
    description:
      "Keyframe timeline editor with easing curves and live preview",
    category: "design",
    tags: [
      "CSS",
      "animation",
      "keyframes",
      "easing",
      "timeline",
      "transition",
    ],
    status: "planned",
    dependencies: "light",
    related: ["flexbox-playground", "grid-playground", "box-shadow"],
  },
  {
    slug: "glassmorphism",
    name: "Glassmorphism Generator",
    description: "Create frosted glass effects with CSS output",
    category: "design",
    tags: ["glassmorphism", "frosted glass", "CSS", "blur", "effect"],
    status: "planned",
    dependencies: "light",
    related: ["neumorphism", "box-shadow", "gradient-generator"],
  },
  {
    slug: "neumorphism",
    name: "Neumorphism Generator",
    description: "Design soft UI elements with shadows",
    category: "design",
    tags: ["neumorphism", "soft UI", "CSS", "shadow", "design"],
    status: "planned",
    dependencies: "light",
    related: ["glassmorphism", "box-shadow", "border-radius"],
  },
  {
    slug: "pattern-generator",
    name: "Pattern / Texture Generator",
    description: "Generate repeating CSS/SVG patterns",
    category: "design",
    tags: ["pattern", "texture", "CSS", "SVG", "repeating", "background"],
    status: "planned",
    dependencies: "light",
    related: ["gradient-generator", "generative-art", "css-art"],
  },
  {
    slug: "mockup-generator",
    name: "Mockup Frame Generator",
    description: "Place screenshots into device frames",
    category: "design",
    tags: ["mockup", "device frame", "screenshot", "presentation"],
    status: "planned",
    dependencies: "light",
    related: ["image-resizer", "placeholder-image", "watermark"],
  },
  {
    slug: "sprite-sheet",
    name: "Sprite Sheet Generator",
    description: "Upload frames and stitch into a spritesheet",
    category: "design",
    tags: ["sprite sheet", "animation", "frames", "game", "CSS sprite"],
    status: "planned",
    dependencies: "light",
    related: ["pixel-art", "image-resizer", "collage-maker"],
  },
  {
    slug: "svg-optimizer",
    name: "SVG Optimizer / Viewer",
    description: "Paste SVG markup, preview, and optimize",
    category: "design",
    tags: ["SVG", "optimize", "viewer", "markup", "clean"],
    status: "planned",
    dependencies: "light",
    related: ["favicon-generator", "pattern-generator", "image-converter"],
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description:
      "Generate favicons in all sizes from text, emoji, or image",
    category: "design",
    tags: ["favicon", "icon", "generator", "ICO", "sizes"],
    status: "planned",
    dependencies: "medium",
    related: ["svg-optimizer", "image-resizer", "placeholder-image"],
  },
  {
    slug: "tailwind-colors",
    name: "Tailwind Color Lookup",
    description: "Browse and search the full Tailwind color palette",
    category: "design",
    tags: ["Tailwind", "color", "palette", "CSS", "lookup"],
    status: "planned",
    dependencies: "light",
    related: ["color-picker", "palette-generator", "contrast-checker"],
  },
  {
    slug: "type-scale",
    name: "Typography Scale Calculator",
    description:
      "Generate a modular type scale from a base size and ratio",
    category: "design",
    tags: ["typography", "scale", "modular", "font size", "ratio"],
    status: "planned",
    dependencies: "light",
    related: ["font-pairing", "color-picker", "contrast-checker"],
  },

  // ─── Image & Media ─────────────────────────────────────────────────
  {
    slug: "image-resizer",
    name: "Image Resizer & Cropper",
    description: "Resize, crop, and adjust images using Canvas API",
    category: "image",
    tags: ["image", "resize", "crop", "canvas", "dimensions"],
    status: "featured",
    dependencies: "light",
    related: ["image-compressor", "image-converter", "watermark"],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Reduce file size with adjustable quality",
    category: "image",
    tags: ["image", "compress", "quality", "file size", "optimize"],
    status: "planned",
    dependencies: "light",
    related: ["image-resizer", "image-converter", "image-to-base64"],
  },
  {
    slug: "image-converter",
    name: "Image Format Converter",
    description: "Convert between PNG, JPEG, WebP, BMP",
    category: "image",
    tags: ["image", "convert", "PNG", "JPEG", "WebP", "BMP", "format"],
    status: "planned",
    dependencies: "light",
    related: ["image-resizer", "image-compressor", "image-to-base64"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert image to Base64 data URI",
    category: "image",
    tags: ["image", "base64", "data URI", "encode"],
    status: "planned",
    dependencies: "light",
    related: ["base64", "image-converter", "image-compressor"],
  },
  {
    slug: "exif-viewer",
    name: "EXIF Data Viewer",
    description: "Inspect embedded photo metadata",
    category: "image",
    tags: ["EXIF", "metadata", "photo", "camera", "GPS", "lens"],
    status: "planned",
    dependencies: "medium",
    related: ["metadata-stripper", "image-resizer", "image-converter"],
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for URLs, text, Wi-Fi, vCards",
    category: "image",
    tags: ["QR code", "generator", "URL", "Wi-Fi", "vCard", "barcode"],
    status: "featured",
    dependencies: "medium",
    related: ["qr-reader", "barcode-generator", "base64"],
  },
  {
    slug: "qr-reader",
    name: "QR Code Reader",
    description: "Scan QR codes from image or camera",
    category: "image",
    tags: ["QR code", "reader", "scanner", "camera", "decode"],
    status: "planned",
    dependencies: "medium",
    related: ["qr-generator", "barcode-generator", "exif-viewer"],
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Create Code128, EAN, UPC barcodes",
    category: "image",
    tags: ["barcode", "Code128", "EAN", "UPC", "generator"],
    status: "planned",
    dependencies: "medium",
    related: ["qr-generator", "qr-reader", "uuid-generator"],
  },
  {
    slug: "ascii-art",
    name: "ASCII Art Generator",
    description: "Convert images to ASCII art",
    category: "image",
    tags: ["ASCII", "art", "image", "text", "convert"],
    status: "planned",
    dependencies: "light",
    related: ["pixel-art", "image-resizer", "generative-art"],
  },
  {
    slug: "pixel-art",
    name: "Pixel Art Editor",
    description: "Grid-based drawing tool with palette and export",
    category: "image",
    tags: ["pixel art", "drawing", "grid", "palette", "editor"],
    status: "live",
    dependencies: "light",
    related: ["drawing-canvas", "ascii-art", "sprite-sheet"],
  },
  {
    slug: "placeholder-image",
    name: "Placeholder Image Generator",
    description: "Generate solid/gradient placeholder images",
    category: "image",
    tags: ["placeholder", "image", "generator", "solid", "gradient"],
    status: "planned",
    dependencies: "light",
    related: ["image-resizer", "favicon-generator", "mockup-generator"],
  },
  {
    slug: "color-replacer",
    name: "Image Color Replacer",
    description: "Swap specific colors in an image using Canvas",
    category: "image",
    tags: ["color", "replace", "swap", "image", "canvas"],
    status: "planned",
    dependencies: "light",
    related: ["color-picker", "duotone-filter", "image-resizer"],
  },
  {
    slug: "collage-maker",
    name: "Photo Collage Maker",
    description: "Arrange multiple images into grid layouts",
    category: "image",
    tags: ["collage", "photo", "grid", "layout", "combine"],
    status: "planned",
    dependencies: "light",
    related: ["image-resizer", "sprite-sheet", "watermark"],
  },
  {
    slug: "watermark",
    name: "Watermark Tool",
    description: "Add text or image watermarks to photos",
    category: "image",
    tags: ["watermark", "text", "image", "overlay", "protect"],
    status: "planned",
    dependencies: "light",
    related: ["image-resizer", "meme-generator", "collage-maker"],
  },
  {
    slug: "audio-trimmer",
    name: "Audio Trimmer",
    description: "Trim audio clips in-browser using Web Audio API",
    category: "image",
    tags: ["audio", "trim", "cut", "Web Audio", "clip"],
    status: "planned",
    dependencies: "light",
    related: ["waveform-visualizer", "screen-recorder", "video-to-gif"],
  },
  {
    slug: "video-to-gif",
    name: "Video to GIF Converter",
    description: "Extract video frames into animated GIF",
    category: "image",
    tags: ["video", "GIF", "convert", "frames", "animation"],
    status: "planned",
    dependencies: "massive",
    related: ["screen-recorder", "audio-trimmer", "pixel-art"],
  },
  {
    slug: "waveform-visualizer",
    name: "Waveform Visualizer",
    description: "Upload audio and see its waveform on Canvas",
    category: "image",
    tags: ["waveform", "audio", "visualizer", "canvas", "wave"],
    status: "planned",
    dependencies: "light",
    related: ["audio-trimmer", "drum-machine", "ambient-sounds"],
  },
  {
    slug: "screen-recorder",
    name: "Screen Recorder",
    description: "Record screen/tab using MediaRecorder API",
    category: "image",
    tags: ["screen", "record", "capture", "MediaRecorder", "video"],
    status: "planned",
    dependencies: "light",
    related: ["webcam-booth", "video-to-gif", "audio-trimmer"],
  },
  {
    slug: "webcam-booth",
    name: "Webcam Photo Booth",
    description: "Capture webcam snapshots with filters",
    category: "image",
    tags: ["webcam", "camera", "photo", "capture", "filter"],
    status: "planned",
    dependencies: "light",
    related: ["screen-recorder", "image-resizer", "watermark"],
  },

  // ─── Math & Data ───────────────────────────────────────────────────
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description:
      "Convert length, weight, volume, temperature, speed, area, data",
    category: "math",
    tags: [
      "unit",
      "convert",
      "length",
      "weight",
      "volume",
      "temperature",
      "metric",
      "imperial",
    ],
    status: "featured",
    dependencies: "light",
    related: ["data-size-converter", "currency-converter", "number-base-converter"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, percentage change, ratios",
    category: "math",
    tags: ["percentage", "calculator", "ratio", "change", "math"],
    status: "live",
    dependencies: "light",
    related: ["unit-converter", "statistics-calculator", "roi-calculator"],
  },
  {
    slug: "number-base-converter",
    name: "Hex / Binary / Decimal Converter",
    description: "Convert between hex, binary, octal, decimal",
    category: "math",
    tags: ["hex", "binary", "decimal", "octal", "base", "converter"],
    status: "live",
    dependencies: "light",
    related: ["bitwise-visualizer", "arbitrary-base-converter", "binary-teacher"],
  },
  {
    slug: "matrix-calculator",
    name: "Matrix Calculator",
    description: "Add, multiply, transpose, invert, determinants",
    category: "math",
    tags: ["matrix", "calculator", "linear algebra", "determinant", "inverse"],
    status: "planned",
    dependencies: "light",
    related: ["statistics-calculator", "scientific-calculator", "boolean-algebra"],
  },
  {
    slug: "statistics-calculator",
    name: "Statistics Calculator",
    description: "Mean, median, mode, std dev, variance, quartiles",
    category: "math",
    tags: [
      "statistics",
      "mean",
      "median",
      "mode",
      "standard deviation",
      "variance",
    ],
    status: "planned",
    dependencies: "light",
    related: ["percentage-calculator", "graphing-calculator", "probability-calculator"],
  },
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    description: "Full calculator with trig, log, exponents, history",
    category: "math",
    tags: [
      "calculator",
      "scientific",
      "trigonometry",
      "logarithm",
      "exponent",
    ],
    status: "planned",
    dependencies: "light",
    related: ["graphing-calculator", "statistics-calculator", "matrix-calculator"],
  },
  {
    slug: "graphing-calculator",
    name: "Graphing Calculator",
    description: "Plot mathematical functions on coordinate plane",
    category: "math",
    tags: ["graph", "plot", "function", "coordinate", "math", "visualize"],
    status: "planned",
    dependencies: "heavy",
    related: ["scientific-calculator", "statistics-calculator", "algorithm-visualizer"],
  },
  {
    slug: "boolean-algebra",
    name: "Boolean Algebra Simplifier",
    description: "Simplify logic expressions and generate truth tables",
    category: "math",
    tags: [
      "boolean",
      "algebra",
      "logic",
      "truth table",
      "simplify",
      "gates",
    ],
    status: "planned",
    dependencies: "light",
    related: ["bitwise-visualizer", "number-base-converter", "scientific-calculator"],
  },
  {
    slug: "roman-numerals",
    name: "Roman Numeral Converter",
    description: "Convert between Roman and Arabic numbers",
    category: "math",
    tags: ["Roman", "numeral", "converter", "Arabic", "number"],
    status: "live",
    dependencies: "light",
    related: ["number-base-converter", "number-to-words", "unit-converter"],
  },
  {
    slug: "number-to-words",
    name: "Number to Words",
    description: "Convert numeric values to written English",
    category: "math",
    tags: ["number", "words", "text", "English", "converter"],
    status: "planned",
    dependencies: "light",
    related: ["roman-numerals", "number-base-converter", "unit-converter"],
  },
  {
    slug: "bitwise-visualizer",
    name: "Bitwise Operation Visualizer",
    description: "Visualize AND, OR, XOR, NOT, shifts bit-by-bit",
    category: "math",
    tags: ["bitwise", "AND", "OR", "XOR", "shift", "binary", "visualizer"],
    status: "planned",
    dependencies: "light",
    related: ["number-base-converter", "boolean-algebra", "chmod-calculator"],
  },
  {
    slug: "probability-calculator",
    name: "Probability Calculator",
    description: "Permutations, combinations, dice, cards",
    category: "math",
    tags: [
      "probability",
      "permutation",
      "combination",
      "dice",
      "cards",
      "statistics",
    ],
    status: "planned",
    dependencies: "light",
    related: ["statistics-calculator", "random-generator", "dice-roller"],
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    description: "Calculate and convert aspect ratios",
    category: "math",
    tags: ["aspect ratio", "16:9", "4:3", "resolution", "dimensions"],
    status: "live",
    dependencies: "light",
    related: ["image-resizer", "unit-converter", "percentage-calculator"],
  },
  {
    slug: "data-size-converter",
    name: "Data Size Converter",
    description: "Convert between bytes, KB, MB, GB, TB",
    category: "math",
    tags: [
      "data size",
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "binary",
      "storage",
    ],
    status: "live",
    dependencies: "light",
    related: ["unit-converter", "bandwidth-calculator", "file-size-analyzer"],
  },
  {
    slug: "random-generator",
    name: "Random Number Generator",
    description: "Random numbers, dice, coins, lottery",
    category: "math",
    tags: ["random", "number", "generator", "dice", "coin", "lottery"],
    status: "live",
    dependencies: "light",
    related: ["dice-roller", "password-generator", "probability-calculator"],
  },
  {
    slug: "arbitrary-base-converter",
    name: "Number Base Converter",
    description:
      "Convert between any base (2–36) with step-by-step",
    category: "math",
    tags: ["base", "convert", "radix", "step-by-step", "number system"],
    status: "planned",
    dependencies: "light",
    related: ["number-base-converter", "binary-teacher", "bitwise-visualizer"],
  },

  // ─── Finance & Business ────────────────────────────────────────────
  {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "Growth over time with chart",
    category: "finance",
    tags: [
      "compound interest",
      "calculator",
      "growth",
      "investment",
      "savings",
    ],
    status: "planned",
    dependencies: "light",
    related: ["mortgage-calculator", "roi-calculator", "savings-goal"],
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage / Loan Calculator",
    description: "Monthly payments, amortization, total interest",
    category: "finance",
    tags: ["mortgage", "loan", "calculator", "amortization", "payment"],
    status: "featured",
    dependencies: "light",
    related: ["compound-interest", "debt-calculator", "budget-planner"],
  },
  {
    slug: "tip-calculator",
    name: "Tip / Bill Splitter",
    description: "Split bills with custom tip and rounding",
    category: "finance",
    tags: ["tip", "bill", "split", "calculator", "restaurant"],
    status: "live",
    dependencies: "light",
    related: ["percentage-calculator", "currency-converter", "salary-converter"],
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert between currencies",
    category: "finance",
    tags: ["currency", "exchange", "converter", "money", "forex"],
    status: "planned",
    dependencies: "light",
    related: ["unit-converter", "tip-calculator", "salary-converter"],
  },
  {
    slug: "subscription-tracker",
    name: "Subscription Tracker",
    description: "List subscriptions, see totals",
    category: "finance",
    tags: ["subscription", "tracker", "recurring", "monthly", "cost"],
    status: "planned",
    dependencies: "light",
    related: ["budget-planner", "savings-goal", "net-worth-tracker"],
  },
  {
    slug: "net-worth-tracker",
    name: "Net Worth Tracker",
    description: "Track assets and liabilities over time",
    category: "finance",
    tags: ["net worth", "assets", "liabilities", "tracker", "wealth"],
    status: "planned",
    dependencies: "light",
    related: ["subscription-tracker", "savings-goal", "budget-planner"],
  },
  {
    slug: "budget-planner",
    name: "50/30/20 Budget Planner",
    description: "Allocate income into needs, wants, savings",
    category: "finance",
    tags: ["budget", "50/30/20", "planner", "income", "allocation"],
    status: "planned",
    dependencies: "light",
    related: ["subscription-tracker", "salary-converter", "savings-goal"],
  },
  {
    slug: "debt-calculator",
    name: "Debt Snowball/Avalanche Calculator",
    description: "Compare payoff strategies",
    category: "finance",
    tags: ["debt", "snowball", "avalanche", "payoff", "strategy"],
    status: "planned",
    dependencies: "light",
    related: ["mortgage-calculator", "compound-interest", "budget-planner"],
  },
  {
    slug: "tax-estimator",
    name: "Tax Estimator (Freelancer)",
    description: "Rough tax estimate by income and deductions",
    category: "finance",
    tags: ["tax", "estimator", "freelancer", "income", "deductions"],
    status: "planned",
    dependencies: "light",
    related: ["salary-converter", "budget-planner", "roi-calculator"],
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description: "Create invoices and export to PDF",
    category: "finance",
    tags: ["invoice", "PDF", "generator", "billing", "business"],
    status: "live",
    dependencies: "heavy",
    related: ["tax-estimator", "salary-converter", "markup-margin"],
  },
  {
    slug: "salary-converter",
    name: "Salary ↔ Hourly Converter",
    description:
      "Convert between annual, monthly, weekly, daily, hourly",
    category: "finance",
    tags: ["salary", "hourly", "converter", "wage", "annual", "monthly"],
    status: "live",
    dependencies: "light",
    related: ["tip-calculator", "tax-estimator", "budget-planner"],
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description: "Return on investment with periods",
    category: "finance",
    tags: ["ROI", "return", "investment", "calculator", "profit"],
    status: "live",
    dependencies: "light",
    related: ["compound-interest", "break-even", "percentage-calculator"],
  },
  {
    slug: "break-even",
    name: "Break-Even Calculator",
    description: "Find break-even point",
    category: "finance",
    tags: ["break-even", "calculator", "business", "profit", "cost"],
    status: "planned",
    dependencies: "light",
    related: ["roi-calculator", "markup-margin", "compound-interest"],
  },
  {
    slug: "savings-goal",
    name: "Savings Goal Tracker",
    description: "Set goals, log deposits, track progress",
    category: "finance",
    tags: ["savings", "goal", "tracker", "deposits", "progress"],
    status: "planned",
    dependencies: "light",
    related: ["budget-planner", "compound-interest", "net-worth-tracker"],
  },
  {
    slug: "position-size",
    name: "Stock Position Size Calculator",
    description: "Position sizing based on risk",
    category: "finance",
    tags: ["stock", "position", "size", "risk", "trading"],
    status: "planned",
    dependencies: "light",
    related: ["roi-calculator", "percentage-calculator", "compound-interest"],
  },
  {
    slug: "markup-margin",
    name: "Markup / Margin Calculator",
    description: "Convert between cost, markup %, profit margin",
    category: "finance",
    tags: ["markup", "margin", "profit", "cost", "percentage"],
    status: "live",
    dependencies: "light",
    related: ["percentage-calculator", "break-even", "roi-calculator"],
  },

  // ─── Security & Privacy ────────────────────────────────────────────
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Strong passwords with customizable options",
    category: "security",
    tags: [
      "password",
      "generator",
      "strong",
      "secure",
      "random",
      "entropy",
    ],
    status: "featured",
    dependencies: "light",
    related: ["password-strength", "random-bytes", "encrypted-vault"],
  },
  {
    slug: "password-strength",
    name: "Password Strength Checker",
    description: "Strength analysis with crack time",
    category: "security",
    tags: ["password", "strength", "checker", "security", "crack time"],
    status: "planned",
    dependencies: "light",
    related: ["password-generator", "hash-generator", "encrypted-vault"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "SHA-1, SHA-256, SHA-512, MD5 of text or files",
    category: "security",
    tags: ["hash", "SHA", "MD5", "SHA-256", "checksum", "digest"],
    status: "live",
    dependencies: "light",
    related: ["checksum-verifier", "hmac-generator", "password-generator"],
  },
  {
    slug: "checksum-verifier",
    name: "File Checksum Verifier",
    description: "Drag-and-drop file hash verification",
    category: "security",
    tags: ["checksum", "verify", "file", "hash", "integrity"],
    status: "planned",
    dependencies: "light",
    related: ["hash-generator", "hmac-generator", "file-size-analyzer"],
  },
  {
    slug: "encrypted-notes",
    name: "Encrypted Notes",
    description: "AES-GCM encrypted notepad",
    category: "security",
    tags: ["encrypted", "notes", "AES", "secure", "notepad", "privacy"],
    status: "planned",
    dependencies: "light",
    related: ["encrypted-vault", "notepad", "secure-share"],
  },
  {
    slug: "encrypted-vault",
    name: "Encrypted Vault",
    description: "Client-side password manager",
    category: "security",
    tags: [
      "vault",
      "password manager",
      "encrypted",
      "secure",
      "PBKDF2",
    ],
    status: "planned",
    dependencies: "light",
    related: ["encrypted-notes", "password-generator", "totp-generator"],
  },
  {
    slug: "hmac-generator",
    name: "HMAC Generator",
    description: "Generate HMAC signatures",
    category: "security",
    tags: ["HMAC", "signature", "hash", "authentication", "crypto"],
    status: "live",
    dependencies: "light",
    related: ["hash-generator", "jwt-builder", "totp-generator"],
  },
  {
    slug: "random-bytes",
    name: "Random Byte Generator",
    description: "Cryptographically secure random bytes",
    category: "security",
    tags: ["random", "bytes", "cryptographic", "hex", "base64"],
    status: "live",
    dependencies: "light",
    related: ["password-generator", "uuid-generator", "hash-generator"],
  },
  {
    slug: "totp-generator",
    name: "TOTP Code Generator",
    description: "Time-based one-time passwords (RFC 6238)",
    category: "security",
    tags: ["TOTP", "2FA", "OTP", "authenticator", "RFC 6238"],
    status: "planned",
    dependencies: "light",
    related: ["hmac-generator", "encrypted-vault", "password-generator"],
  },
  {
    slug: "metadata-stripper",
    name: "Privacy Metadata Stripper",
    description: "Remove EXIF from images before sharing",
    category: "security",
    tags: ["EXIF", "metadata", "strip", "privacy", "image"],
    status: "planned",
    dependencies: "light",
    related: ["exif-viewer", "image-resizer", "hash-generator"],
  },
  {
    slug: "secure-share",
    name: "Secure Text Sharing Encoder",
    description:
      "Encode message into a URL fragment for client-side decryption",
    category: "security",
    tags: ["secure", "share", "encrypt", "URL", "message", "privacy"],
    status: "planned",
    dependencies: "light",
    related: ["encrypted-notes", "base64", "password-generator"],
  },

  // ─── Productivity ──────────────────────────────────────────────────
  {
    slug: "pomodoro",
    name: "Pomodoro Timer",
    description:
      "Focus timer with configurable intervals and session tracking",
    category: "productivity",
    tags: ["pomodoro", "timer", "focus", "productivity", "interval"],
    status: "featured",
    dependencies: "light",
    related: ["stopwatch", "countdown", "hiit-timer"],
  },
  {
    slug: "stopwatch",
    name: "Stopwatch & Lap Timer",
    description: "Precision stopwatch with lap recording",
    category: "productivity",
    tags: ["stopwatch", "lap", "timer", "precision", "split"],
    status: "live",
    dependencies: "light",
    related: ["pomodoro", "countdown", "meeting-cost"],
  },
  {
    slug: "countdown",
    name: "Countdown Timer",
    description: "Count down to a specific date",
    category: "productivity",
    tags: ["countdown", "timer", "date", "event", "days"],
    status: "live",
    dependencies: "light",
    related: ["pomodoro", "stopwatch", "age-calculator"],
  },
  {
    slug: "kanban",
    name: "Kanban Board",
    description: "Drag-and-drop task board",
    category: "productivity",
    tags: ["kanban", "board", "tasks", "drag and drop", "project"],
    status: "live",
    dependencies: "light",
    related: ["todo-list", "eisenhower-matrix", "daily-planner"],
  },
  {
    slug: "todo-list",
    name: "To-Do List / Checklist",
    description: "Task manager with priorities and due dates",
    category: "productivity",
    tags: ["todo", "checklist", "tasks", "priority", "due date"],
    status: "planned",
    dependencies: "light",
    related: ["kanban", "eisenhower-matrix", "goal-tracker"],
  },
  {
    slug: "habit-tracker",
    name: "Habit Tracker",
    description: "Daily habits with streaks and heatmap",
    category: "productivity",
    tags: ["habit", "tracker", "streak", "heatmap", "daily"],
    status: "live",
    dependencies: "light",
    related: ["goal-tracker", "todo-list", "pomodoro"],
  },
  {
    slug: "notepad",
    name: "Notepad with Auto-Save",
    description: "Distraction-free writing pad",
    category: "productivity",
    tags: ["notepad", "writing", "auto-save", "distraction-free", "text"],
    status: "live",
    dependencies: "light",
    related: ["markdown-editor", "encrypted-notes", "sticky-notes"],
  },
  {
    slug: "meeting-cost",
    name: "Meeting Cost Calculator",
    description: "Calculate real cost of a meeting",
    category: "productivity",
    tags: ["meeting", "cost", "calculator", "salary", "time"],
    status: "planned",
    dependencies: "light",
    related: ["salary-converter", "stopwatch", "pomodoro"],
  },
  {
    slug: "decision-matrix",
    name: "Decision Matrix",
    description: "Score options against weighted criteria",
    category: "productivity",
    tags: ["decision", "matrix", "weighted", "criteria", "score"],
    status: "planned",
    dependencies: "light",
    related: ["eisenhower-matrix", "kanban", "todo-list"],
  },
  {
    slug: "eisenhower-matrix",
    name: "Eisenhower Matrix",
    description: "Drag tasks into urgent/important quadrants",
    category: "productivity",
    tags: [
      "eisenhower",
      "matrix",
      "urgent",
      "important",
      "prioritize",
    ],
    status: "planned",
    dependencies: "light",
    related: ["decision-matrix", "kanban", "todo-list"],
  },
  {
    slug: "mind-map",
    name: "Mind Map Builder",
    description: "Branching mind maps with drag-and-drop",
    category: "productivity",
    tags: ["mind map", "brainstorm", "diagram", "branch", "ideas"],
    status: "planned",
    dependencies: "light",
    related: ["kanban", "sticky-notes", "decision-matrix"],
  },
  {
    slug: "daily-planner",
    name: "Daily Planner / Schedule",
    description: "Time-block your day",
    category: "productivity",
    tags: ["planner", "schedule", "time block", "daily", "calendar"],
    status: "planned",
    dependencies: "light",
    related: ["pomodoro", "kanban", "todo-list"],
  },
  {
    slug: "reading-time",
    name: "Reading Time Estimator",
    description: "Estimate reading time at various speeds",
    category: "productivity",
    tags: ["reading time", "WPM", "estimate", "speed", "words"],
    status: "live",
    dependencies: "light",
    related: ["word-counter", "word-frequency", "typing-test"],
  },
  {
    slug: "sticky-notes",
    name: "Sticky Notes Wall",
    description: "Freeform draggable sticky notes",
    category: "productivity",
    tags: ["sticky notes", "drag", "freeform", "notes", "wall"],
    status: "planned",
    dependencies: "light",
    related: ["notepad", "kanban", "mind-map"],
  },
  {
    slug: "goal-tracker",
    name: "Goal Tracker",
    description: "Goals with milestones and progress bars",
    category: "productivity",
    tags: ["goal", "tracker", "milestone", "progress", "achievement"],
    status: "planned",
    dependencies: "light",
    related: ["habit-tracker", "savings-goal", "todo-list"],
  },

  // ─── Health & Fitness ──────────────────────────────────────────────
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Body Mass Index with visual scale",
    category: "health",
    tags: ["BMI", "body mass index", "weight", "health", "calculator"],
    status: "live",
    dependencies: "light",
    related: ["tdee-calculator", "calorie-counter", "one-rep-max"],
  },
  {
    slug: "tdee-calculator",
    name: "TDEE & Macro Calculator",
    description: "Daily calorie needs and macro targets",
    category: "health",
    tags: ["TDEE", "calories", "macros", "nutrition", "daily"],
    status: "planned",
    dependencies: "light",
    related: ["bmi-calculator", "calorie-counter", "water-tracker"],
  },
  {
    slug: "water-tracker",
    name: "Water Intake Tracker",
    description: "Log daily water consumption",
    category: "health",
    tags: ["water", "intake", "tracker", "hydration", "daily"],
    status: "planned",
    dependencies: "light",
    related: ["calorie-counter", "habit-tracker", "tdee-calculator"],
  },
  {
    slug: "sleep-calculator",
    name: "Sleep Cycle Calculator",
    description: "Optimal bedtimes based on 90-min cycles",
    category: "health",
    tags: ["sleep", "cycle", "bedtime", "wake up", "90 minutes"],
    status: "live",
    dependencies: "light",
    related: ["pomodoro", "breathing-timer", "daily-planner"],
  },
  {
    slug: "hiit-timer",
    name: "HIIT / Tabata Timer",
    description: "Customizable interval timer with audio",
    category: "health",
    tags: ["HIIT", "tabata", "interval", "timer", "workout", "exercise"],
    status: "planned",
    dependencies: "light",
    related: ["pomodoro", "stopwatch", "breathing-timer"],
  },
  {
    slug: "body-tracker",
    name: "Body Measurement Tracker",
    description: "Log measurements over time with charts",
    category: "health",
    tags: ["body", "measurement", "tracker", "chest", "waist", "chart"],
    status: "planned",
    dependencies: "light",
    related: ["bmi-calculator", "habit-tracker", "goal-tracker"],
  },
  {
    slug: "calorie-counter",
    name: "Calorie Counter",
    description: "Calorie lookup and daily logging",
    category: "health",
    tags: ["calorie", "counter", "food", "nutrition", "daily", "log"],
    status: "planned",
    dependencies: "light",
    related: ["tdee-calculator", "bmi-calculator", "water-tracker"],
  },
  {
    slug: "one-rep-max",
    name: "One-Rep Max Calculator",
    description: "Estimate 1RM from submaximal lifts",
    category: "health",
    tags: ["1RM", "one rep max", "strength", "lifting", "calculator"],
    status: "planned",
    dependencies: "light",
    related: ["bmi-calculator", "hiit-timer", "body-tracker"],
  },
  {
    slug: "pace-calculator",
    name: "Pace Calculator",
    description: "Convert pace, speed, and finish time",
    category: "health",
    tags: ["pace", "speed", "running", "finish time", "calculator"],
    status: "planned",
    dependencies: "light",
    related: ["unit-converter", "stopwatch", "hiit-timer"],
  },
  {
    slug: "breathing-timer",
    name: "Breathing Exercise Timer",
    description: "Guided breathing with visual + audio",
    category: "health",
    tags: [
      "breathing",
      "exercise",
      "meditation",
      "box breathing",
      "4-7-8",
    ],
    status: "planned",
    dependencies: "light",
    related: ["pomodoro", "sleep-calculator", "hiit-timer"],
  },

  // ─── Networking & Sysadmin ─────────────────────────────────────────
  {
    slug: "subnet-calculator",
    name: "Subnet Calculator",
    description: "Network, broadcast, host range from IP + CIDR",
    category: "networking",
    tags: ["subnet", "IP", "CIDR", "network", "broadcast", "host"],
    status: "live",
    dependencies: "light",
    related: ["ip-converter", "cidr-visualizer", "netmask-calculator"],
  },
  {
    slug: "ip-converter",
    name: "IPv4 ↔ IPv6 Converter",
    description: "Convert between IPv4 and IPv6",
    category: "networking",
    tags: ["IPv4", "IPv6", "convert", "IP address"],
    status: "planned",
    dependencies: "light",
    related: ["subnet-calculator", "cidr-visualizer", "netmask-calculator"],
  },
  {
    slug: "cidr-visualizer",
    name: "CIDR Range Visualizer",
    description: "See which IPs fall within a CIDR block",
    category: "networking",
    tags: ["CIDR", "range", "IP", "visualize", "block"],
    status: "planned",
    dependencies: "light",
    related: ["subnet-calculator", "ip-converter", "netmask-calculator"],
  },
  {
    slug: "bandwidth-calculator",
    name: "Bandwidth Calculator",
    description: "Transfer time for file size at given speed",
    category: "networking",
    tags: ["bandwidth", "transfer", "speed", "file size", "download"],
    status: "planned",
    dependencies: "light",
    related: ["data-size-converter", "subnet-calculator", "unit-converter"],
  },
  {
    slug: "dns-reference",
    name: "DNS Record Reference",
    description: "Interactive DNS record type reference",
    category: "networking",
    tags: ["DNS", "record", "A", "CNAME", "MX", "reference"],
    status: "planned",
    dependencies: "light",
    related: ["port-reference", "http-status-codes", "subnet-calculator"],
  },
  {
    slug: "port-reference",
    name: "Port Number Reference",
    description: "Searchable common port database",
    category: "networking",
    tags: ["port", "number", "service", "reference", "TCP", "UDP"],
    status: "planned",
    dependencies: "light",
    related: ["dns-reference", "http-status-codes", "mac-lookup"],
  },
  {
    slug: "mac-lookup",
    name: "MAC Address Lookup",
    description: "Identify vendor from OUI prefix",
    category: "networking",
    tags: ["MAC", "address", "OUI", "vendor", "lookup"],
    status: "planned",
    dependencies: "light",
    related: ["port-reference", "subnet-calculator", "dns-reference"],
  },
  {
    slug: "netmask-calculator",
    name: "Network Mask Calculator",
    description: "Convert between dotted-decimal, CIDR, wildcard",
    category: "networking",
    tags: ["netmask", "CIDR", "wildcard", "dotted-decimal", "subnet"],
    status: "planned",
    dependencies: "light",
    related: ["subnet-calculator", "cidr-visualizer", "ip-converter"],
  },

  // ─── Education & Learning ──────────────────────────────────────────
  {
    slug: "typing-test",
    name: "Typing Speed Test",
    description: "WPM with accuracy and difficulty levels",
    category: "education",
    tags: ["typing", "speed", "WPM", "accuracy", "test", "practice"],
    status: "featured",
    dependencies: "light",
    related: ["mental-math", "reading-time", "flashcards"],
  },
  {
    slug: "flashcards",
    name: "Flashcard App",
    description: "Spaced repetition (Leitner) stored locally",
    category: "education",
    tags: [
      "flashcard",
      "spaced repetition",
      "Leitner",
      "study",
      "memorize",
    ],
    status: "live",
    dependencies: "light",
    related: ["vocabulary-builder", "typing-test", "mental-math"],
  },
  {
    slug: "mental-math",
    name: "Mental Math Trainer",
    description: "Timed arithmetic drills",
    category: "education",
    tags: ["mental math", "arithmetic", "drill", "practice", "timed"],
    status: "planned",
    dependencies: "light",
    related: ["times-tables", "typing-test", "flashcards"],
  },
  {
    slug: "periodic-table",
    name: "Periodic Table Explorer",
    description: "Interactive periodic table",
    category: "education",
    tags: [
      "periodic table",
      "elements",
      "chemistry",
      "science",
      "interactive",
    ],
    status: "planned",
    dependencies: "light",
    related: ["unit-converter", "binary-teacher", "algorithm-visualizer"],
  },
  {
    slug: "geography-quiz",
    name: "Geography Quiz",
    description: "Identify countries on SVG world map",
    category: "education",
    tags: ["geography", "quiz", "countries", "map", "world"],
    status: "planned",
    dependencies: "light",
    related: ["typing-test", "flashcards", "mental-math"],
  },
  {
    slug: "interval-trainer",
    name: "Music Interval Trainer",
    description: "Hear two notes, guess the interval",
    category: "education",
    tags: ["music", "interval", "ear training", "notes", "audio"],
    status: "planned",
    dependencies: "light",
    related: ["drum-machine", "morse-code", "mental-math"],
  },
  {
    slug: "vocabulary-builder",
    name: "Language Vocabulary Builder",
    description: "Words + translations with spaced repetition",
    category: "education",
    tags: ["vocabulary", "language", "translation", "spaced repetition"],
    status: "planned",
    dependencies: "light",
    related: ["flashcards", "typing-test", "mental-math"],
  },
  {
    slug: "times-tables",
    name: "Times Table Trainer",
    description: "Multiplication drills with visual feedback",
    category: "education",
    tags: ["times table", "multiplication", "drill", "math", "kids"],
    status: "planned",
    dependencies: "light",
    related: ["mental-math", "flashcards", "typing-test"],
  },
  {
    slug: "color-blind-sim",
    name: "Color Blindness Simulator",
    description: "Preview images with color vision deficiencies",
    category: "education",
    tags: [
      "color blindness",
      "CVD",
      "accessibility",
      "simulator",
      "vision",
    ],
    status: "planned",
    dependencies: "light",
    related: ["contrast-checker", "color-picker", "image-resizer"],
  },
  {
    slug: "binary-teacher",
    name: "Binary / Hex Teaching Tool",
    description: "Interactive binary ↔ decimal ↔ hex",
    category: "education",
    tags: ["binary", "hex", "decimal", "teaching", "interactive", "bits"],
    status: "planned",
    dependencies: "light",
    related: [
      "number-base-converter",
      "arbitrary-base-converter",
      "bitwise-visualizer",
    ],
  },
  {
    slug: "algorithm-visualizer",
    name: "Algorithm Visualizer",
    description: "Watch sorting/search algorithms step-by-step",
    category: "education",
    tags: [
      "algorithm",
      "sorting",
      "search",
      "visualizer",
      "bubble sort",
      "quicksort",
    ],
    status: "live",
    dependencies: "light",
    related: ["graphing-calculator", "binary-teacher", "boolean-algebra"],
  },

  // ─── Fun & Creative ────────────────────────────────────────────────
  {
    slug: "drum-machine",
    name: "Drum Machine / Beat Maker",
    description: "Sequencer with Web Audio API",
    category: "fun",
    tags: [
      "drum machine",
      "beat",
      "music",
      "sequencer",
      "Web Audio",
      "rhythm",
    ],
    status: "live",
    dependencies: "light",
    related: ["ambient-sounds", "soundboard", "interval-trainer"],
  },
  {
    slug: "generative-art",
    name: "Generative Art Tool",
    description: "Parameter-driven pattern creation",
    category: "fun",
    tags: [
      "generative",
      "art",
      "pattern",
      "fractal",
      "creative",
      "canvas",
    ],
    status: "planned",
    dependencies: "light",
    related: ["drawing-canvas", "terrain-generator", "css-art"],
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description: "Upload image, add draggable text overlays",
    category: "fun",
    tags: ["meme", "generator", "image", "text", "funny", "caption"],
    status: "planned",
    dependencies: "light",
    related: ["watermark", "image-resizer", "drawing-canvas"],
  },
  {
    slug: "soundboard",
    name: "Soundboard",
    description: "Upload and trigger audio clips",
    category: "fun",
    tags: ["soundboard", "audio", "clips", "trigger", "effects"],
    status: "planned",
    dependencies: "light",
    related: ["drum-machine", "ambient-sounds", "audio-trimmer"],
  },
  {
    slug: "game-of-life",
    name: "Conway's Game of Life",
    description: "Cellular automaton",
    category: "fun",
    tags: [
      "Conway",
      "Game of Life",
      "cellular automaton",
      "simulation",
      "grid",
    ],
    status: "live",
    dependencies: "light",
    related: ["terrain-generator", "generative-art", "pixel-art"],
  },
  {
    slug: "terrain-generator",
    name: "Procedural Terrain Generator",
    description: "Landscape generation using noise",
    category: "fun",
    tags: [
      "terrain",
      "procedural",
      "noise",
      "Perlin",
      "landscape",
      "generation",
    ],
    status: "planned",
    dependencies: "light",
    related: ["generative-art", "game-of-life", "pixel-art"],
  },
  {
    slug: "drawing-canvas",
    name: "Drawing Canvas",
    description: "Freehand drawing with brushes",
    category: "fun",
    tags: ["drawing", "canvas", "paint", "brush", "freehand", "art"],
    status: "planned",
    dependencies: "light",
    related: ["pixel-art", "generative-art", "meme-generator"],
  },
  {
    slug: "magic-8-ball",
    name: "Fortune / Magic 8-Ball",
    description: "Random answers with animation",
    category: "fun",
    tags: ["magic 8-ball", "fortune", "random", "fun", "animation"],
    status: "live",
    dependencies: "light",
    related: ["dice-roller", "random-generator", "palette-game"],
  },
  {
    slug: "dice-roller",
    name: "Dice Roller (D&D)",
    description: "Roll polyhedral dice with history",
    category: "fun",
    tags: ["dice", "roller", "D&D", "polyhedral", "d20", "RPG"],
    status: "live",
    dependencies: "light",
    related: ["random-generator", "magic-8-ball", "probability-calculator"],
  },
  {
    slug: "ambient-sounds",
    name: "Noise / Ambient Sound Generator",
    description: "Layer noise and nature sounds",
    category: "fun",
    tags: ["ambient", "noise", "white noise", "nature", "sounds", "relax"],
    status: "planned",
    dependencies: "light",
    related: ["drum-machine", "soundboard", "breathing-timer"],
  },
  {
    slug: "css-art",
    name: "CSS Art Playground",
    description: "Create illustrations using only CSS",
    category: "fun",
    tags: ["CSS", "art", "illustration", "playground", "creative"],
    status: "planned",
    dependencies: "light",
    related: ["generative-art", "pattern-generator", "animation-builder"],
  },
  {
    slug: "emoji-search",
    name: "Emoji Picker / Search",
    description: "Search emojis with copy to clipboard",
    category: "fun",
    tags: ["emoji", "picker", "search", "copy", "unicode"],
    status: "planned",
    dependencies: "light",
    related: ["unicode-lookup", "name-generator", "zalgo-text"],
  },
  {
    slug: "palette-game",
    name: "Random Color Palette Game",
    description: "Vote on random palettes to train color sense",
    category: "fun",
    tags: ["color", "palette", "game", "vote", "design"],
    status: "planned",
    dependencies: "light",
    related: ["palette-generator", "color-picker", "magic-8-ball"],
  },

  // ─── File Utilities ────────────────────────────────────────────────
  {
    slug: "pdf-merger",
    name: "PDF Merger",
    description: "Combine multiple PDFs into one",
    category: "files",
    tags: ["PDF", "merge", "combine", "join", "document"],
    status: "live",
    dependencies: "heavy",
    related: ["pdf-splitter", "pdf-rotator", "text-merger"],
  },
  {
    slug: "pdf-splitter",
    name: "PDF Splitter",
    description: "Extract specific pages from a PDF",
    category: "files",
    tags: ["PDF", "split", "extract", "pages", "document"],
    status: "planned",
    dependencies: "heavy",
    related: ["pdf-merger", "pdf-rotator", "text-merger"],
  },
  {
    slug: "pdf-rotator",
    name: "PDF Page Rotator",
    description: "Rotate pages in a PDF",
    category: "files",
    tags: ["PDF", "rotate", "pages", "orientation", "document"],
    status: "planned",
    dependencies: "heavy",
    related: ["pdf-merger", "pdf-splitter", "image-resizer"],
  },
  {
    slug: "file-size-analyzer",
    name: "File Size Analyzer",
    description: "Drag-and-drop file size breakdown",
    category: "files",
    tags: ["file size", "analyzer", "breakdown", "chart", "storage"],
    status: "planned",
    dependencies: "light",
    related: ["data-size-converter", "checksum-verifier", "zip-creator"],
  },
  {
    slug: "text-merger",
    name: "Text File Merger",
    description: "Concatenate multiple text/CSV files",
    category: "files",
    tags: ["text", "merge", "concatenate", "CSV", "file"],
    status: "planned",
    dependencies: "light",
    related: ["pdf-merger", "json-to-csv", "text-cleaner"],
  },
  {
    slug: "markdown-to-html",
    name: "Markdown → HTML Converter",
    description: "Convert Markdown to clean HTML",
    category: "files",
    tags: ["markdown", "HTML", "convert", "export"],
    status: "live",
    dependencies: "medium",
    related: ["html-to-markdown", "markdown-editor", "json-formatter"],
  },
  {
    slug: "html-to-markdown",
    name: "HTML → Markdown Converter",
    description: "Turn HTML into Markdown",
    category: "files",
    tags: ["HTML", "markdown", "convert", "turndown"],
    status: "live",
    dependencies: "medium",
    related: ["markdown-to-html", "markdown-editor", "html-entities"],
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV Exporter",
    description: "Flatten JSON arrays into CSV",
    category: "files",
    tags: ["JSON", "CSV", "export", "flatten", "table"],
    status: "live",
    dependencies: "light",
    related: ["csv-json", "json-formatter", "text-merger"],
  },
  {
    slug: "zip-creator",
    name: "ZIP File Creator",
    description: "Bundle files into a .zip",
    category: "files",
    tags: ["ZIP", "archive", "compress", "bundle", "file"],
    status: "planned",
    dependencies: "heavy",
    related: ["file-renamer", "file-size-analyzer", "pdf-merger"],
  },
  {
    slug: "file-renamer",
    name: "File Rename Batch Tool",
    description: "Batch rename with patterns",
    category: "files",
    tags: ["rename", "batch", "pattern", "file", "bulk"],
    status: "planned",
    dependencies: "heavy",
    related: ["zip-creator", "file-size-analyzer", "text-merger"],
  },
  {
    slug: "text-cleaner",
    name: "Plain Text Cleaner",
    description: "Fix encoding, remove smart quotes, normalize",
    category: "files",
    tags: [
      "text",
      "clean",
      "encoding",
      "smart quotes",
      "normalize",
      "whitespace",
    ],
    status: "planned",
    dependencies: "light",
    related: ["whitespace-cleaner", "text-merger", "html-to-markdown"],
  },

  // ─── Date & Time ───────────────────────────────────────────────────
  {
    slug: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert time across multiple timezones",
    category: "datetime",
    tags: ["timezone", "convert", "time", "UTC", "Intl"],
    status: "planned",
    dependencies: "light",
    related: ["meeting-planner", "timestamp-converter", "date-difference"],
  },
  {
    slug: "date-difference",
    name: "Date Difference Calculator",
    description: "Days, weeks, months, years between dates",
    category: "datetime",
    tags: ["date", "difference", "days", "between", "calculator"],
    status: "live",
    dependencies: "light",
    related: ["date-add-subtract", "age-calculator", "working-days"],
  },
  {
    slug: "date-add-subtract",
    name: "Date Adder/Subtractor",
    description: "Add or subtract time from a date",
    category: "datetime",
    tags: ["date", "add", "subtract", "calculate", "future", "past"],
    status: "planned",
    dependencies: "light",
    related: ["date-difference", "working-days", "age-calculator"],
  },
  {
    slug: "week-number",
    name: "Week Number Lookup",
    description: "ISO week number for any date",
    category: "datetime",
    tags: ["week", "number", "ISO", "date", "lookup"],
    status: "planned",
    dependencies: "light",
    related: ["date-difference", "calendar-generator", "working-days"],
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Exact age in years, months, days",
    category: "datetime",
    tags: ["age", "birthday", "calculator", "years", "months", "days"],
    status: "live",
    dependencies: "light",
    related: ["date-difference", "countdown", "relative-time"],
  },
  {
    slug: "working-days",
    name: "Working Days Calculator",
    description: "Business days between two dates",
    category: "datetime",
    tags: ["working days", "business days", "weekdays", "calculator"],
    status: "planned",
    dependencies: "light",
    related: ["date-difference", "date-add-subtract", "meeting-planner"],
  },
  {
    slug: "calendar-generator",
    name: "Calendar Generator",
    description: "Printable monthly/yearly calendars",
    category: "datetime",
    tags: ["calendar", "generator", "monthly", "yearly", "print"],
    status: "planned",
    dependencies: "light",
    related: ["week-number", "daily-planner", "date-difference"],
  },
  {
    slug: "meeting-planner",
    name: "Timezone Meeting Planner",
    description: "Find overlapping working hours",
    category: "datetime",
    tags: ["meeting", "timezone", "planner", "overlap", "schedule"],
    status: "planned",
    dependencies: "light",
    related: ["timezone-converter", "working-days", "daily-planner"],
  },
  {
    slug: "relative-time",
    name: "Relative Time Display",
    description: "See dates as relative strings",
    category: "datetime",
    tags: ["relative", "time", "ago", "from now", "display"],
    status: "planned",
    dependencies: "light",
    related: ["timestamp-converter", "age-calculator", "date-difference"],
  },
];

// ─── Helper Functions ──────────────────────────────────────────────────

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.category === categorySlug);
}

export function getLiveToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter(
    (t) =>
      t.category === categorySlug &&
      (t.status === "live" || t.status === "featured" || t.status === "beta")
  );
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((t) => t.status === "featured");
}

export function getAllTools(): Tool[] {
  return tools;
}

export function getVisibleTools(): Tool[] {
  return tools.filter((t) => t.status !== "deprecated");
}

export function isToolAccessible(tool: Tool): boolean {
  return tool.status === "live" || tool.status === "featured" || tool.status === "beta";
}
